// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: _bootstrap.sql

package pgdb

import (
	"context"
)

const healthcheck = `-- name: Healthcheck :one
SELECT 1 AS ok
`

func (q *Queries) Healthcheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthcheck)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
