// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (
    id,
    name,
    description,
    key_hash,
    key_prefix,
    user_id,
    environment_id,
    expires_at,
    last_used_at,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
RETURNING id, name, description, key_hash, key_prefix, user_id, environment_id, expires_at, last_used_at, created_at, updated_at
`

type CreateApiKeyParams struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	KeyHash       string             `json:"key_hash"`
	KeyPrefix     string             `json:"key_prefix"`
	UserID        string             `json:"user_id"`
	EnvironmentID pgtype.Text        `json:"environment_id"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
}

type CreateApiKeyRow struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	KeyHash       string             `json:"key_hash"`
	KeyPrefix     string             `json:"key_prefix"`
	UserID        string             `json:"user_id"`
	EnvironmentID pgtype.Text        `json:"environment_id"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (*CreateApiKeyRow, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.UserID,
		arg.EnvironmentID,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	var i CreateApiKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.UserID,
		&i.EnvironmentID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteApiKeyByID = `-- name: DeleteApiKeyByID :execrows
DELETE FROM api_keys
WHERE id = $1
`

func (q *Queries) DeleteApiKeyByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApiKeyByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApiKeyByID = `-- name: GetApiKeyByID :one
SELECT id, name, description, key_hash, key_prefix, user_id, environment_id, expires_at, last_used_at, created_at, updated_at
FROM api_keys
WHERE id = $1
LIMIT 1
`

type GetApiKeyByIDRow struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	KeyHash       string             `json:"key_hash"`
	KeyPrefix     string             `json:"key_prefix"`
	UserID        string             `json:"user_id"`
	EnvironmentID pgtype.Text        `json:"environment_id"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetApiKeyByID(ctx context.Context, id string) (*GetApiKeyByIDRow, error) {
	row := q.db.QueryRow(ctx, getApiKeyByID, id)
	var i GetApiKeyByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.UserID,
		&i.EnvironmentID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listApiKeys = `-- name: ListApiKeys :many
SELECT id, name, description, key_hash, key_prefix, user_id, environment_id, expires_at, last_used_at, created_at, updated_at
FROM api_keys
`

type ListApiKeysRow struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	KeyHash       string             `json:"key_hash"`
	KeyPrefix     string             `json:"key_prefix"`
	UserID        string             `json:"user_id"`
	EnvironmentID pgtype.Text        `json:"environment_id"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListApiKeys(ctx context.Context) ([]*ListApiKeysRow, error) {
	rows, err := q.db.Query(ctx, listApiKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListApiKeysRow{}
	for rows.Next() {
		var i ListApiKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.UserID,
			&i.EnvironmentID,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiKeysByPrefix = `-- name: ListApiKeysByPrefix :many
SELECT id, name, description, key_hash, key_prefix, user_id, environment_id, expires_at, last_used_at, created_at, updated_at
FROM api_keys
WHERE key_prefix = $1
`

type ListApiKeysByPrefixRow struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	KeyHash       string             `json:"key_hash"`
	KeyPrefix     string             `json:"key_prefix"`
	UserID        string             `json:"user_id"`
	EnvironmentID pgtype.Text        `json:"environment_id"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListApiKeysByPrefix(ctx context.Context, keyPrefix string) ([]*ListApiKeysByPrefixRow, error) {
	rows, err := q.db.Query(ctx, listApiKeysByPrefix, keyPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListApiKeysByPrefixRow{}
	for rows.Next() {
		var i ListApiKeysByPrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.UserID,
			&i.EnvironmentID,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchApiKeyLastUsed = `-- name: TouchApiKeyLastUsed :exec
UPDATE api_keys
SET
    last_used_at = $2,
    updated_at = NOW()
WHERE id = $1
`

type TouchApiKeyLastUsedParams struct {
	ID         string             `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) TouchApiKeyLastUsed(ctx context.Context, arg TouchApiKeyLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchApiKeyLastUsed, arg.ID, arg.LastUsedAt)
	return err
}

const updateApiKey = `-- name: UpdateApiKey :exec
UPDATE api_keys
SET
    name = $2,
    description = $3,
    expires_at = $4,
    updated_at = NOW()
WHERE id = $1
`

type UpdateApiKeyParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateApiKey(ctx context.Context, arg UpdateApiKeyParams) error {
	_, err := q.db.Exec(ctx, updateApiKey,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ExpiresAt,
	)
	return err
}
