// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apprise_settings.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppriseSettings = `-- name: CreateAppriseSettings :one
INSERT INTO apprise_settings (api_url, enabled, image_update_tag, container_update_tag)
VALUES ($1, $2, $3, $4)
RETURNING id, api_url, enabled, image_update_tag, container_update_tag, created_at, updated_at
`

type CreateAppriseSettingsParams struct {
	ApiUrl             string      `json:"api_url"`
	Enabled            pgtype.Bool `json:"enabled"`
	ImageUpdateTag     pgtype.Text `json:"image_update_tag"`
	ContainerUpdateTag pgtype.Text `json:"container_update_tag"`
}

func (q *Queries) CreateAppriseSettings(ctx context.Context, arg CreateAppriseSettingsParams) (*AppriseSetting, error) {
	row := q.db.QueryRow(ctx, createAppriseSettings,
		arg.ApiUrl,
		arg.Enabled,
		arg.ImageUpdateTag,
		arg.ContainerUpdateTag,
	)
	var i AppriseSetting
	err := row.Scan(
		&i.ID,
		&i.ApiUrl,
		&i.Enabled,
		&i.ImageUpdateTag,
		&i.ContainerUpdateTag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAppriseSettings = `-- name: GetAppriseSettings :one
SELECT id, api_url, enabled, image_update_tag, container_update_tag, created_at, updated_at
FROM apprise_settings
ORDER BY id ASC
LIMIT 1
`

func (q *Queries) GetAppriseSettings(ctx context.Context) (*AppriseSetting, error) {
	row := q.db.QueryRow(ctx, getAppriseSettings)
	var i AppriseSetting
	err := row.Scan(
		&i.ID,
		&i.ApiUrl,
		&i.Enabled,
		&i.ImageUpdateTag,
		&i.ContainerUpdateTag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateAppriseSettings = `-- name: UpdateAppriseSettings :one
UPDATE apprise_settings
SET api_url = $2,
    enabled = $3,
    image_update_tag = $4,
    container_update_tag = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, api_url, enabled, image_update_tag, container_update_tag, created_at, updated_at
`

type UpdateAppriseSettingsParams struct {
	ID                 int32       `json:"id"`
	ApiUrl             string      `json:"api_url"`
	Enabled            pgtype.Bool `json:"enabled"`
	ImageUpdateTag     pgtype.Text `json:"image_update_tag"`
	ContainerUpdateTag pgtype.Text `json:"container_update_tag"`
}

func (q *Queries) UpdateAppriseSettings(ctx context.Context, arg UpdateAppriseSettingsParams) (*AppriseSetting, error) {
	row := q.db.QueryRow(ctx, updateAppriseSettings,
		arg.ID,
		arg.ApiUrl,
		arg.Enabled,
		arg.ImageUpdateTag,
		arg.ContainerUpdateTag,
	)
	var i AppriseSetting
	err := row.Scan(
		&i.ID,
		&i.ApiUrl,
		&i.Enabled,
		&i.ImageUpdateTag,
		&i.ContainerUpdateTag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
