// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: container_registries.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContainerRegistry = `-- name: CreateContainerRegistry :one
INSERT INTO container_registries (
    id,
    url,
    username,
    token,
    description,
    insecure,
    enabled,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, url, username, token, description, insecure, enabled, created_at, updated_at
`

type CreateContainerRegistryParams struct {
	ID          string      `json:"id"`
	Url         string      `json:"url"`
	Username    string      `json:"username"`
	Token       string      `json:"token"`
	Description pgtype.Text `json:"description"`
	Insecure    bool        `json:"insecure"`
	Enabled     bool        `json:"enabled"`
}

func (q *Queries) CreateContainerRegistry(ctx context.Context, arg CreateContainerRegistryParams) (*ContainerRegistry, error) {
	row := q.db.QueryRow(ctx, createContainerRegistry,
		arg.ID,
		arg.Url,
		arg.Username,
		arg.Token,
		arg.Description,
		arg.Insecure,
		arg.Enabled,
	)
	var i ContainerRegistry
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Username,
		&i.Token,
		&i.Description,
		&i.Insecure,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteContainerRegistryByID = `-- name: DeleteContainerRegistryByID :execrows
DELETE FROM container_registries
WHERE id = $1
`

func (q *Queries) DeleteContainerRegistryByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContainerRegistryByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getContainerRegistryByID = `-- name: GetContainerRegistryByID :one
SELECT id, url, username, token, description, insecure, enabled, created_at, updated_at
FROM container_registries
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetContainerRegistryByID(ctx context.Context, id string) (*ContainerRegistry, error) {
	row := q.db.QueryRow(ctx, getContainerRegistryByID, id)
	var i ContainerRegistry
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Username,
		&i.Token,
		&i.Description,
		&i.Insecure,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listContainerRegistries = `-- name: ListContainerRegistries :many
SELECT id, url, username, token, description, insecure, enabled, created_at, updated_at
FROM container_registries
`

func (q *Queries) ListContainerRegistries(ctx context.Context) ([]*ContainerRegistry, error) {
	rows, err := q.db.Query(ctx, listContainerRegistries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ContainerRegistry{}
	for rows.Next() {
		var i ContainerRegistry
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Username,
			&i.Token,
			&i.Description,
			&i.Insecure,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledContainerRegistries = `-- name: ListEnabledContainerRegistries :many
SELECT id, url, username, token, description, insecure, enabled, created_at, updated_at
FROM container_registries
WHERE enabled = true
`

func (q *Queries) ListEnabledContainerRegistries(ctx context.Context) ([]*ContainerRegistry, error) {
	rows, err := q.db.Query(ctx, listEnabledContainerRegistries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ContainerRegistry{}
	for rows.Next() {
		var i ContainerRegistry
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Username,
			&i.Token,
			&i.Description,
			&i.Insecure,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContainerRegistry = `-- name: UpdateContainerRegistry :exec
UPDATE container_registries
SET
    url = $2,
    username = $3,
    token = $4,
    description = $5,
    insecure = $6,
    enabled = $7,
    updated_at = NOW()
WHERE id = $1
`

type UpdateContainerRegistryParams struct {
	ID          string      `json:"id"`
	Url         string      `json:"url"`
	Username    string      `json:"username"`
	Token       string      `json:"token"`
	Description pgtype.Text `json:"description"`
	Insecure    bool        `json:"insecure"`
	Enabled     bool        `json:"enabled"`
}

func (q *Queries) UpdateContainerRegistry(ctx context.Context, arg UpdateContainerRegistryParams) error {
	_, err := q.db.Exec(ctx, updateContainerRegistry,
		arg.ID,
		arg.Url,
		arg.Username,
		arg.Token,
		arg.Description,
		arg.Insecure,
		arg.Enabled,
	)
	return err
}
