// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package pgdb

import (
	"context"

	"github.com/getarcaneapp/arcane/types/base"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    id,
    type,
    severity,
    title,
    description,
    resource_type,
    resource_id,
    resource_name,
    user_id,
    username,
    environment_id,
    metadata,
    timestamp,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, type, severity, title, description, resource_type, resource_id, resource_name, user_id, username, environment_id, metadata, timestamp, created_at, updated_at
`

type CreateEventParams struct {
	ID            string             `json:"id"`
	Type          string             `json:"type"`
	Severity      string             `json:"severity"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	ResourceType  pgtype.Text        `json:"resource_type"`
	ResourceID    pgtype.Text        `json:"resource_id"`
	ResourceName  pgtype.Text        `json:"resource_name"`
	UserID        pgtype.Text        `json:"user_id"`
	Username      pgtype.Text        `json:"username"`
	EnvironmentID pgtype.Text        `json:"environment_id"`
	Metadata      base.JSON          `json:"metadata"`
	Timestamp     pgtype.Timestamptz `json:"timestamp"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (*Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.Type,
		arg.Severity,
		arg.Title,
		arg.Description,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourceName,
		arg.UserID,
		arg.Username,
		arg.EnvironmentID,
		arg.Metadata,
		arg.Timestamp,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Severity,
		&i.Title,
		&i.Description,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceName,
		&i.UserID,
		&i.Username,
		&i.EnvironmentID,
		&i.Metadata,
		&i.Timestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteEventByID = `-- name: DeleteEventByID :execrows
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEventByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEventsOlderThan = `-- name: DeleteEventsOlderThan :execrows
DELETE FROM events
WHERE timestamp < $1
`

func (q *Queries) DeleteEventsOlderThan(ctx context.Context, timestamp pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventsOlderThan, timestamp)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, type, severity, title, description, resource_type, resource_id, resource_name, user_id, username, environment_id, metadata, timestamp, created_at, updated_at
FROM events
`

func (q *Queries) ListEvents(ctx context.Context) ([]*Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Severity,
			&i.Title,
			&i.Description,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceName,
			&i.UserID,
			&i.Username,
			&i.EnvironmentID,
			&i.Metadata,
			&i.Timestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
