// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gitops_syncs.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearProjectGitOpsManagedByIfMatches = `-- name: ClearProjectGitOpsManagedByIfMatches :exec
UPDATE projects
SET gitops_managed_by = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND gitops_managed_by = $2
`

type ClearProjectGitOpsManagedByIfMatchesParams struct {
	ID              string      `json:"id"`
	GitopsManagedBy pgtype.Text `json:"gitops_managed_by"`
}

func (q *Queries) ClearProjectGitOpsManagedByIfMatches(ctx context.Context, arg ClearProjectGitOpsManagedByIfMatchesParams) error {
	_, err := q.db.Exec(ctx, clearProjectGitOpsManagedByIfMatches, arg.ID, arg.GitopsManagedBy)
	return err
}

const createGitOpsSync = `-- name: CreateGitOpsSync :one
INSERT INTO gitops_syncs (
    id,
    name,
    environment_id,
    repository_id,
    branch,
    compose_path,
    project_name,
    project_id,
    auto_sync,
    sync_interval,
    last_sync_at,
    last_sync_status,
    last_sync_error,
    last_sync_commit,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, name, repository_id, branch, compose_path, project_name, project_id, auto_sync, sync_interval, last_sync_at, last_sync_status, last_sync_error, last_sync_commit, environment_id, created_at, updated_at
`

type CreateGitOpsSyncParams struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	EnvironmentID  string             `json:"environment_id"`
	RepositoryID   string             `json:"repository_id"`
	Branch         string             `json:"branch"`
	ComposePath    string             `json:"compose_path"`
	ProjectName    string             `json:"project_name"`
	ProjectID      pgtype.Text        `json:"project_id"`
	AutoSync       bool               `json:"auto_sync"`
	SyncInterval   int32              `json:"sync_interval"`
	LastSyncAt     pgtype.Timestamptz `json:"last_sync_at"`
	LastSyncStatus pgtype.Text        `json:"last_sync_status"`
	LastSyncError  pgtype.Text        `json:"last_sync_error"`
	LastSyncCommit pgtype.Text        `json:"last_sync_commit"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateGitOpsSync(ctx context.Context, arg CreateGitOpsSyncParams) (*GitopsSync, error) {
	row := q.db.QueryRow(ctx, createGitOpsSync,
		arg.ID,
		arg.Name,
		arg.EnvironmentID,
		arg.RepositoryID,
		arg.Branch,
		arg.ComposePath,
		arg.ProjectName,
		arg.ProjectID,
		arg.AutoSync,
		arg.SyncInterval,
		arg.LastSyncAt,
		arg.LastSyncStatus,
		arg.LastSyncError,
		arg.LastSyncCommit,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GitopsSync
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepositoryID,
		&i.Branch,
		&i.ComposePath,
		&i.ProjectName,
		&i.ProjectID,
		&i.AutoSync,
		&i.SyncInterval,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.LastSyncError,
		&i.LastSyncCommit,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteGitOpsSyncByID = `-- name: DeleteGitOpsSyncByID :execrows
DELETE FROM gitops_syncs
WHERE id = $1
`

func (q *Queries) DeleteGitOpsSyncByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGitOpsSyncByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGitOpsSyncByID = `-- name: GetGitOpsSyncByID :one
SELECT id, name, repository_id, branch, compose_path, project_name, project_id, auto_sync, sync_interval, last_sync_at, last_sync_status, last_sync_error, last_sync_commit, environment_id, created_at, updated_at
FROM gitops_syncs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetGitOpsSyncByID(ctx context.Context, id string) (*GitopsSync, error) {
	row := q.db.QueryRow(ctx, getGitOpsSyncByID, id)
	var i GitopsSync
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepositoryID,
		&i.Branch,
		&i.ComposePath,
		&i.ProjectName,
		&i.ProjectID,
		&i.AutoSync,
		&i.SyncInterval,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.LastSyncError,
		&i.LastSyncCommit,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAutoSyncGitOpsSyncs = `-- name: ListAutoSyncGitOpsSyncs :many
SELECT id, name, repository_id, branch, compose_path, project_name, project_id, auto_sync, sync_interval, last_sync_at, last_sync_status, last_sync_error, last_sync_commit, environment_id, created_at, updated_at
FROM gitops_syncs
WHERE auto_sync = true
`

func (q *Queries) ListAutoSyncGitOpsSyncs(ctx context.Context) ([]*GitopsSync, error) {
	rows, err := q.db.Query(ctx, listAutoSyncGitOpsSyncs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GitopsSync{}
	for rows.Next() {
		var i GitopsSync
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepositoryID,
			&i.Branch,
			&i.ComposePath,
			&i.ProjectName,
			&i.ProjectID,
			&i.AutoSync,
			&i.SyncInterval,
			&i.LastSyncAt,
			&i.LastSyncStatus,
			&i.LastSyncError,
			&i.LastSyncCommit,
			&i.EnvironmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitOpsSyncs = `-- name: ListGitOpsSyncs :many
SELECT id, name, repository_id, branch, compose_path, project_name, project_id, auto_sync, sync_interval, last_sync_at, last_sync_status, last_sync_error, last_sync_commit, environment_id, created_at, updated_at
FROM gitops_syncs
`

func (q *Queries) ListGitOpsSyncs(ctx context.Context) ([]*GitopsSync, error) {
	rows, err := q.db.Query(ctx, listGitOpsSyncs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GitopsSync{}
	for rows.Next() {
		var i GitopsSync
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepositoryID,
			&i.Branch,
			&i.ComposePath,
			&i.ProjectName,
			&i.ProjectID,
			&i.AutoSync,
			&i.SyncInterval,
			&i.LastSyncAt,
			&i.LastSyncStatus,
			&i.LastSyncError,
			&i.LastSyncCommit,
			&i.EnvironmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitOpsSyncsByEnvironment = `-- name: ListGitOpsSyncsByEnvironment :many
SELECT id, name, repository_id, branch, compose_path, project_name, project_id, auto_sync, sync_interval, last_sync_at, last_sync_status, last_sync_error, last_sync_commit, environment_id, created_at, updated_at
FROM gitops_syncs
WHERE environment_id = $1
`

func (q *Queries) ListGitOpsSyncsByEnvironment(ctx context.Context, environmentID string) ([]*GitopsSync, error) {
	rows, err := q.db.Query(ctx, listGitOpsSyncsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GitopsSync{}
	for rows.Next() {
		var i GitopsSync
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepositoryID,
			&i.Branch,
			&i.ComposePath,
			&i.ProjectName,
			&i.ProjectID,
			&i.AutoSync,
			&i.SyncInterval,
			&i.LastSyncAt,
			&i.LastSyncStatus,
			&i.LastSyncError,
			&i.LastSyncCommit,
			&i.EnvironmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveGitOpsSync = `-- name: SaveGitOpsSync :one
UPDATE gitops_syncs
SET
    name = $1,
    environment_id = $2,
    repository_id = $3,
    branch = $4,
    compose_path = $5,
    project_name = $6,
    project_id = $7,
    auto_sync = $8,
    sync_interval = $9,
    last_sync_at = $10,
    last_sync_status = $11,
    last_sync_error = $12,
    last_sync_commit = $13,
    updated_at = $14
WHERE id = $15
RETURNING id, name, repository_id, branch, compose_path, project_name, project_id, auto_sync, sync_interval, last_sync_at, last_sync_status, last_sync_error, last_sync_commit, environment_id, created_at, updated_at
`

type SaveGitOpsSyncParams struct {
	Name           string             `json:"name"`
	EnvironmentID  string             `json:"environment_id"`
	RepositoryID   string             `json:"repository_id"`
	Branch         string             `json:"branch"`
	ComposePath    string             `json:"compose_path"`
	ProjectName    string             `json:"project_name"`
	ProjectID      pgtype.Text        `json:"project_id"`
	AutoSync       bool               `json:"auto_sync"`
	SyncInterval   int32              `json:"sync_interval"`
	LastSyncAt     pgtype.Timestamptz `json:"last_sync_at"`
	LastSyncStatus pgtype.Text        `json:"last_sync_status"`
	LastSyncError  pgtype.Text        `json:"last_sync_error"`
	LastSyncCommit pgtype.Text        `json:"last_sync_commit"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ID             string             `json:"id"`
}

func (q *Queries) SaveGitOpsSync(ctx context.Context, arg SaveGitOpsSyncParams) (*GitopsSync, error) {
	row := q.db.QueryRow(ctx, saveGitOpsSync,
		arg.Name,
		arg.EnvironmentID,
		arg.RepositoryID,
		arg.Branch,
		arg.ComposePath,
		arg.ProjectName,
		arg.ProjectID,
		arg.AutoSync,
		arg.SyncInterval,
		arg.LastSyncAt,
		arg.LastSyncStatus,
		arg.LastSyncError,
		arg.LastSyncCommit,
		arg.UpdatedAt,
		arg.ID,
	)
	var i GitopsSync
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepositoryID,
		&i.Branch,
		&i.ComposePath,
		&i.ProjectName,
		&i.ProjectID,
		&i.AutoSync,
		&i.SyncInterval,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.LastSyncError,
		&i.LastSyncCommit,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const setProjectGitOpsManagedBy = `-- name: SetProjectGitOpsManagedBy :exec
UPDATE projects
SET gitops_managed_by = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type SetProjectGitOpsManagedByParams struct {
	GitopsManagedBy pgtype.Text `json:"gitops_managed_by"`
	ID              string      `json:"id"`
}

func (q *Queries) SetProjectGitOpsManagedBy(ctx context.Context, arg SetProjectGitOpsManagedByParams) error {
	_, err := q.db.Exec(ctx, setProjectGitOpsManagedBy, arg.GitopsManagedBy, arg.ID)
	return err
}

const updateGitOpsSyncInterval = `-- name: UpdateGitOpsSyncInterval :exec
UPDATE gitops_syncs
SET sync_interval = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateGitOpsSyncIntervalParams struct {
	SyncInterval int32  `json:"sync_interval"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateGitOpsSyncInterval(ctx context.Context, arg UpdateGitOpsSyncIntervalParams) error {
	_, err := q.db.Exec(ctx, updateGitOpsSyncInterval, arg.SyncInterval, arg.ID)
	return err
}

const updateGitOpsSyncProjectID = `-- name: UpdateGitOpsSyncProjectID :exec
UPDATE gitops_syncs
SET project_id = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateGitOpsSyncProjectIDParams struct {
	ProjectID pgtype.Text `json:"project_id"`
	ID        string      `json:"id"`
}

func (q *Queries) UpdateGitOpsSyncProjectID(ctx context.Context, arg UpdateGitOpsSyncProjectIDParams) error {
	_, err := q.db.Exec(ctx, updateGitOpsSyncProjectID, arg.ProjectID, arg.ID)
	return err
}

const updateGitOpsSyncStatus = `-- name: UpdateGitOpsSyncStatus :exec
UPDATE gitops_syncs
SET
    last_sync_at = $1,
    last_sync_status = $2,
    last_sync_error = $3,
    last_sync_commit = $4,
    updated_at = $1
WHERE id = $5
`

type UpdateGitOpsSyncStatusParams struct {
	LastSyncAt     pgtype.Timestamptz `json:"last_sync_at"`
	LastSyncStatus pgtype.Text        `json:"last_sync_status"`
	LastSyncError  pgtype.Text        `json:"last_sync_error"`
	LastSyncCommit pgtype.Text        `json:"last_sync_commit"`
	ID             string             `json:"id"`
}

func (q *Queries) UpdateGitOpsSyncStatus(ctx context.Context, arg UpdateGitOpsSyncStatusParams) error {
	_, err := q.db.Exec(ctx, updateGitOpsSyncStatus,
		arg.LastSyncAt,
		arg.LastSyncStatus,
		arg.LastSyncError,
		arg.LastSyncCommit,
		arg.ID,
	)
	return err
}
