// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"github.com/getarcaneapp/arcane/types/base"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	KeyHash       string             `json:"key_hash"`
	KeyPrefix     string             `json:"key_prefix"`
	UserID        string             `json:"user_id"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	EnvironmentID pgtype.Text        `json:"environment_id"`
}

type AppriseSetting struct {
	ID                 int32            `json:"id"`
	ApiUrl             string           `json:"api_url"`
	Enabled            pgtype.Bool      `json:"enabled"`
	ImageUpdateTag     pgtype.Text      `json:"image_update_tag"`
	ContainerUpdateTag pgtype.Text      `json:"container_update_tag"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type AutoUpdateRecord struct {
	ID               string             `json:"id"`
	ResourceID       string             `json:"resource_id"`
	ResourceType     string             `json:"resource_type"`
	ResourceName     string             `json:"resource_name"`
	Status           string             `json:"status"`
	StartTime        pgtype.Timestamptz `json:"start_time"`
	EndTime          pgtype.Timestamptz `json:"end_time"`
	UpdateAvailable  bool               `json:"update_available"`
	UpdateApplied    bool               `json:"update_applied"`
	OldImageVersions base.JSON          `json:"old_image_versions"`
	NewImageVersions base.JSON          `json:"new_image_versions"`
	Error            pgtype.Text        `json:"error"`
	Details          base.JSON          `json:"details"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ComposeTemplate struct {
	ID                   string             `json:"id"`
	Name                 string             `json:"name"`
	Description          pgtype.Text        `json:"description"`
	Content              pgtype.Text        `json:"content"`
	EnvContent           pgtype.Text        `json:"env_content"`
	IsCustom             bool               `json:"is_custom"`
	IsRemote             bool               `json:"is_remote"`
	RegistryID           pgtype.Text        `json:"registry_id"`
	MetaVersion          pgtype.Text        `json:"meta_version"`
	MetaAuthor           pgtype.Text        `json:"meta_author"`
	MetaTags             pgtype.Text        `json:"meta_tags"`
	MetaRemoteUrl        pgtype.Text        `json:"meta_remote_url"`
	MetaEnvUrl           pgtype.Text        `json:"meta_env_url"`
	MetaDocumentationUrl pgtype.Text        `json:"meta_documentation_url"`
	MetaIconUrl          pgtype.Text        `json:"meta_icon_url"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type ContainerRegistry struct {
	ID          string             `json:"id"`
	Url         string             `json:"url"`
	Username    string             `json:"username"`
	Token       string             `json:"token"`
	Description pgtype.Text        `json:"description"`
	Insecure    bool               `json:"insecure"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Environment struct {
	ID          string             `json:"id"`
	ApiUrl      string             `json:"api_url"`
	Status      string             `json:"status"`
	Enabled     bool               `json:"enabled"`
	LastSeen    pgtype.Timestamptz `json:"last_seen"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AccessToken pgtype.Text        `json:"access_token"`
	Name        pgtype.Text        `json:"name"`
	ApiKeyID    pgtype.Text        `json:"api_key_id"`
	IsEdge      bool               `json:"is_edge"`
}

type Event struct {
	ID            string             `json:"id"`
	Type          string             `json:"type"`
	Severity      string             `json:"severity"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	ResourceType  pgtype.Text        `json:"resource_type"`
	ResourceID    pgtype.Text        `json:"resource_id"`
	ResourceName  pgtype.Text        `json:"resource_name"`
	UserID        pgtype.Text        `json:"user_id"`
	Username      pgtype.Text        `json:"username"`
	EnvironmentID pgtype.Text        `json:"environment_id"`
	Metadata      base.JSON          `json:"metadata"`
	Timestamp     pgtype.Timestamptz `json:"timestamp"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type GitRepository struct {
	ID                     string             `json:"id"`
	Name                   string             `json:"name"`
	Url                    string             `json:"url"`
	AuthType               string             `json:"auth_type"`
	Username               pgtype.Text        `json:"username"`
	Token                  pgtype.Text        `json:"token"`
	SshKey                 pgtype.Text        `json:"ssh_key"`
	Description            pgtype.Text        `json:"description"`
	Enabled                bool               `json:"enabled"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	SshHostKeyVerification string             `json:"ssh_host_key_verification"`
}

type GitopsSync struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	RepositoryID   string             `json:"repository_id"`
	Branch         string             `json:"branch"`
	ComposePath    string             `json:"compose_path"`
	ProjectName    string             `json:"project_name"`
	ProjectID      pgtype.Text        `json:"project_id"`
	AutoSync       bool               `json:"auto_sync"`
	SyncInterval   int32              `json:"sync_interval"`
	LastSyncAt     pgtype.Timestamptz `json:"last_sync_at"`
	LastSyncStatus pgtype.Text        `json:"last_sync_status"`
	LastSyncError  pgtype.Text        `json:"last_sync_error"`
	LastSyncCommit pgtype.Text        `json:"last_sync_commit"`
	EnvironmentID  string             `json:"environment_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Image struct {
	ID          string             `json:"id"`
	RepoTags    base.JSON          `json:"repo_tags"`
	RepoDigests base.JSON          `json:"repo_digests"`
	Size        int64              `json:"size"`
	VirtualSize int64              `json:"virtual_size"`
	Labels      base.JSON          `json:"labels"`
	Created     pgtype.Timestamptz `json:"created"`
	Repo        pgtype.Text        `json:"repo"`
	Tag         pgtype.Text        `json:"tag"`
	InUse       bool               `json:"in_use"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ImageUpdate struct {
	ID               string             `json:"id"`
	Repository       string             `json:"repository"`
	Tag              string             `json:"tag"`
	HasUpdate        bool               `json:"has_update"`
	UpdateType       pgtype.Text        `json:"update_type"`
	CurrentVersion   string             `json:"current_version"`
	LatestVersion    pgtype.Text        `json:"latest_version"`
	CurrentDigest    pgtype.Text        `json:"current_digest"`
	LatestDigest     pgtype.Text        `json:"latest_digest"`
	CheckTime        pgtype.Timestamptz `json:"check_time"`
	ResponseTimeMs   int32              `json:"response_time_ms"`
	LastError        pgtype.Text        `json:"last_error"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AuthMethod       pgtype.Text        `json:"auth_method"`
	AuthUsername     pgtype.Text        `json:"auth_username"`
	AuthRegistry     pgtype.Text        `json:"auth_registry"`
	UsedCredential   pgtype.Bool        `json:"used_credential"`
	NotificationSent pgtype.Bool        `json:"notification_sent"`
}

type NotificationLog struct {
	ID        int32            `json:"id"`
	Provider  string           `json:"provider"`
	ImageRef  string           `json:"image_ref"`
	Status    string           `json:"status"`
	Error     pgtype.Text      `json:"error"`
	Metadata  base.JSON        `json:"metadata"`
	SentAt    pgtype.Timestamp `json:"sent_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type NotificationSetting struct {
	ID        int32            `json:"id"`
	Provider  string           `json:"provider"`
	Enabled   pgtype.Bool      `json:"enabled"`
	Config    base.JSON        `json:"config"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Project struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	DirName         pgtype.Text        `json:"dir_name"`
	Path            string             `json:"path"`
	Status          string             `json:"status"`
	ServiceCount    int32              `json:"service_count"`
	RunningCount    int32              `json:"running_count"`
	AutoUpdate      bool               `json:"auto_update"`
	IsExternal      bool               `json:"is_external"`
	IsLegacy        bool               `json:"is_legacy"`
	IsRemote        bool               `json:"is_remote"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	StatusReason    pgtype.Text        `json:"status_reason"`
	GitopsManagedBy pgtype.Text        `json:"gitops_managed_by"`
}

type Setting struct {
	Key        string             `json:"key"`
	Value      string             `json:"value"`
	Type       string             `json:"type"`
	Ispublic   bool               `json:"ispublic"`
	Isinternal bool               `json:"isinternal"`
	Createdat  pgtype.Timestamptz `json:"createdat"`
	Updatedat  pgtype.Timestamptz `json:"updatedat"`
}

type TemplateRegistry struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Url         string             `json:"url"`
	Enabled     bool               `json:"enabled"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                       string             `json:"id"`
	Username                 string             `json:"username"`
	PasswordHash             string             `json:"password_hash"`
	DisplayName              pgtype.Text        `json:"display_name"`
	Email                    pgtype.Text        `json:"email"`
	Roles                    base.StringSlice   `json:"roles"`
	RequirePasswordChange    bool               `json:"require_password_change"`
	OidcSubjectID            pgtype.Text        `json:"oidc_subject_id"`
	LastLogin                pgtype.Timestamptz `json:"last_login"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	OidcAccessToken          pgtype.Text        `json:"oidc_access_token"`
	OidcRefreshToken         pgtype.Text        `json:"oidc_refresh_token"`
	OidcAccessTokenExpiresAt pgtype.Timestamptz `json:"oidc_access_token_expires_at"`
	Locale                   pgtype.Text        `json:"locale"`
	RequiresPasswordChange   bool               `json:"requires_password_change"`
}

type VolumeBackup struct {
	ID         string             `json:"id"`
	VolumeName string             `json:"volume_name"`
	Size       int64              `json:"size"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
