// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_logs.sql

package pgdb

import (
	"context"

	"github.com/getarcaneapp/arcane/types/base"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationLog = `-- name: CreateNotificationLog :exec
INSERT INTO notification_logs (provider, image_ref, status, error, metadata, sent_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateNotificationLogParams struct {
	Provider string           `json:"provider"`
	ImageRef string           `json:"image_ref"`
	Status   string           `json:"status"`
	Error    pgtype.Text      `json:"error"`
	Metadata base.JSON        `json:"metadata"`
	SentAt   pgtype.Timestamp `json:"sent_at"`
}

func (q *Queries) CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) error {
	_, err := q.db.Exec(ctx, createNotificationLog,
		arg.Provider,
		arg.ImageRef,
		arg.Status,
		arg.Error,
		arg.Metadata,
		arg.SentAt,
	)
	return err
}
