// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_settings.sql

package pgdb

import (
	"context"

	"github.com/getarcaneapp/arcane/types/base"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationSetting = `-- name: CreateNotificationSetting :one
INSERT INTO notification_settings (provider, enabled, config)
VALUES ($1, $2, $3)
RETURNING id, provider, enabled, config, created_at, updated_at
`

type CreateNotificationSettingParams struct {
	Provider string      `json:"provider"`
	Enabled  pgtype.Bool `json:"enabled"`
	Config   base.JSON   `json:"config"`
}

func (q *Queries) CreateNotificationSetting(ctx context.Context, arg CreateNotificationSettingParams) (*NotificationSetting, error) {
	row := q.db.QueryRow(ctx, createNotificationSetting, arg.Provider, arg.Enabled, arg.Config)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Enabled,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteNotificationSettingByProvider = `-- name: DeleteNotificationSettingByProvider :execrows
DELETE FROM notification_settings
WHERE provider = $1
`

func (q *Queries) DeleteNotificationSettingByProvider(ctx context.Context, provider string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationSettingByProvider, provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotificationSettingByProvider = `-- name: GetNotificationSettingByProvider :one
SELECT id, provider, enabled, config, created_at, updated_at
FROM notification_settings
WHERE provider = $1
LIMIT 1
`

func (q *Queries) GetNotificationSettingByProvider(ctx context.Context, provider string) (*NotificationSetting, error) {
	row := q.db.QueryRow(ctx, getNotificationSettingByProvider, provider)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Enabled,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listNotificationSettings = `-- name: ListNotificationSettings :many
SELECT id, provider, enabled, config, created_at, updated_at
FROM notification_settings
ORDER BY id ASC
`

func (q *Queries) ListNotificationSettings(ctx context.Context) ([]*NotificationSetting, error) {
	rows, err := q.db.Query(ctx, listNotificationSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*NotificationSetting{}
	for rows.Next() {
		var i NotificationSetting
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Enabled,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationSetting = `-- name: UpdateNotificationSetting :one
UPDATE notification_settings
SET enabled = $2,
    config = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, provider, enabled, config, created_at, updated_at
`

type UpdateNotificationSettingParams struct {
	ID      int32       `json:"id"`
	Enabled pgtype.Bool `json:"enabled"`
	Config  base.JSON   `json:"config"`
}

func (q *Queries) UpdateNotificationSetting(ctx context.Context, arg UpdateNotificationSettingParams) (*NotificationSetting, error) {
	row := q.db.QueryRow(ctx, updateNotificationSetting, arg.ID, arg.Enabled, arg.Config)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Enabled,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
