// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: template_registries.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplateRegistry = `-- name: CreateTemplateRegistry :one
INSERT INTO template_registries (
    id,
    name,
    url,
    enabled,
    description,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, url, enabled, description, created_at, updated_at
`

type CreateTemplateRegistryParams struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Url         string             `json:"url"`
	Enabled     bool               `json:"enabled"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTemplateRegistry(ctx context.Context, arg CreateTemplateRegistryParams) (*TemplateRegistry, error) {
	row := q.db.QueryRow(ctx, createTemplateRegistry,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Enabled,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TemplateRegistry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteTemplateRegistryByID = `-- name: DeleteTemplateRegistryByID :execrows
DELETE FROM template_registries
WHERE id = $1
`

func (q *Queries) DeleteTemplateRegistryByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTemplateRegistryByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTemplateRegistryByID = `-- name: GetTemplateRegistryByID :one
SELECT id, name, url, enabled, description, created_at, updated_at
FROM template_registries
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTemplateRegistryByID(ctx context.Context, id string) (*TemplateRegistry, error) {
	row := q.db.QueryRow(ctx, getTemplateRegistryByID, id)
	var i TemplateRegistry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listTemplateRegistries = `-- name: ListTemplateRegistries :many
SELECT id, name, url, enabled, description, created_at, updated_at
FROM template_registries
`

func (q *Queries) ListTemplateRegistries(ctx context.Context) ([]*TemplateRegistry, error) {
	rows, err := q.db.Query(ctx, listTemplateRegistries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*TemplateRegistry{}
	for rows.Next() {
		var i TemplateRegistry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Enabled,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveTemplateRegistry = `-- name: SaveTemplateRegistry :one
UPDATE template_registries
SET
    name = $1,
    url = $2,
    enabled = $3,
    description = $4,
    updated_at = $5
WHERE id = $6
RETURNING id, name, url, enabled, description, created_at, updated_at
`

type SaveTemplateRegistryParams struct {
	Name        string             `json:"name"`
	Url         string             `json:"url"`
	Enabled     bool               `json:"enabled"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          string             `json:"id"`
}

func (q *Queries) SaveTemplateRegistry(ctx context.Context, arg SaveTemplateRegistryParams) (*TemplateRegistry, error) {
	row := q.db.QueryRow(ctx, saveTemplateRegistry,
		arg.Name,
		arg.Url,
		arg.Enabled,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	var i TemplateRegistry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Enabled,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
