// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package pgdb

import (
	"context"

	"github.com/getarcaneapp/arcane/types/base"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    username,
    password_hash,
    display_name,
    email,
    roles,
    require_password_change,
    oidc_subject_id,
    last_login,
    created_at,
    updated_at,
    oidc_access_token,
    oidc_refresh_token,
    oidc_access_token_expires_at,
    locale,
    requires_password_change
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
`

type CreateUserParams struct {
	ID                       string             `json:"id"`
	Username                 string             `json:"username"`
	PasswordHash             string             `json:"password_hash"`
	DisplayName              pgtype.Text        `json:"display_name"`
	Email                    pgtype.Text        `json:"email"`
	Roles                    base.StringSlice   `json:"roles"`
	RequirePasswordChange    bool               `json:"require_password_change"`
	OidcSubjectID            pgtype.Text        `json:"oidc_subject_id"`
	LastLogin                pgtype.Timestamptz `json:"last_login"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	OidcAccessToken          pgtype.Text        `json:"oidc_access_token"`
	OidcRefreshToken         pgtype.Text        `json:"oidc_refresh_token"`
	OidcAccessTokenExpiresAt pgtype.Timestamptz `json:"oidc_access_token_expires_at"`
	Locale                   pgtype.Text        `json:"locale"`
	RequiresPasswordChange   bool               `json:"requires_password_change"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Email,
		arg.Roles,
		arg.RequirePasswordChange,
		arg.OidcSubjectID,
		arg.LastLogin,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.OidcAccessToken,
		arg.OidcRefreshToken,
		arg.OidcAccessTokenExpiresAt,
		arg.Locale,
		arg.RequiresPasswordChange,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Roles,
		&i.RequirePasswordChange,
		&i.OidcSubjectID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcAccessToken,
		&i.OidcRefreshToken,
		&i.OidcAccessTokenExpiresAt,
		&i.Locale,
		&i.RequiresPasswordChange,
	)
	return &i, err
}

const deleteUserByID = `-- name: DeleteUserByID :execrows
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Roles,
		&i.RequirePasswordChange,
		&i.OidcSubjectID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcAccessToken,
		&i.OidcRefreshToken,
		&i.OidcAccessTokenExpiresAt,
		&i.Locale,
		&i.RequiresPasswordChange,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Roles,
		&i.RequirePasswordChange,
		&i.OidcSubjectID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcAccessToken,
		&i.OidcRefreshToken,
		&i.OidcAccessTokenExpiresAt,
		&i.Locale,
		&i.RequiresPasswordChange,
	)
	return &i, err
}

const getUserByIDForUpdate = `-- name: GetUserByIDForUpdate :one
SELECT id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
FROM users
WHERE id = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetUserByIDForUpdate(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByIDForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Roles,
		&i.RequirePasswordChange,
		&i.OidcSubjectID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcAccessToken,
		&i.OidcRefreshToken,
		&i.OidcAccessTokenExpiresAt,
		&i.Locale,
		&i.RequiresPasswordChange,
	)
	return &i, err
}

const getUserByOidcSubjectID = `-- name: GetUserByOidcSubjectID :one
SELECT id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
FROM users
WHERE oidc_subject_id = $1
LIMIT 1
`

func (q *Queries) GetUserByOidcSubjectID(ctx context.Context, oidcSubjectID pgtype.Text) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByOidcSubjectID, oidcSubjectID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Roles,
		&i.RequirePasswordChange,
		&i.OidcSubjectID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcAccessToken,
		&i.OidcRefreshToken,
		&i.OidcAccessTokenExpiresAt,
		&i.Locale,
		&i.RequiresPasswordChange,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Roles,
		&i.RequirePasswordChange,
		&i.OidcSubjectID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcAccessToken,
		&i.OidcRefreshToken,
		&i.OidcAccessTokenExpiresAt,
		&i.Locale,
		&i.RequiresPasswordChange,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.DisplayName,
			&i.Email,
			&i.Roles,
			&i.RequirePasswordChange,
			&i.OidcSubjectID,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OidcAccessToken,
			&i.OidcRefreshToken,
			&i.OidcAccessTokenExpiresAt,
			&i.Locale,
			&i.RequiresPasswordChange,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username = $2,
    password_hash = $3,
    display_name = $4,
    email = $5,
    roles = $6,
    require_password_change = $7,
    oidc_subject_id = $8,
    last_login = $9,
    updated_at = $10,
    oidc_access_token = $11,
    oidc_refresh_token = $12,
    oidc_access_token_expires_at = $13,
    locale = $14,
    requires_password_change = $15
WHERE id = $1
RETURNING id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
`

type UpdateUserParams struct {
	ID                       string             `json:"id"`
	Username                 string             `json:"username"`
	PasswordHash             string             `json:"password_hash"`
	DisplayName              pgtype.Text        `json:"display_name"`
	Email                    pgtype.Text        `json:"email"`
	Roles                    base.StringSlice   `json:"roles"`
	RequirePasswordChange    bool               `json:"require_password_change"`
	OidcSubjectID            pgtype.Text        `json:"oidc_subject_id"`
	LastLogin                pgtype.Timestamptz `json:"last_login"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	OidcAccessToken          pgtype.Text        `json:"oidc_access_token"`
	OidcRefreshToken         pgtype.Text        `json:"oidc_refresh_token"`
	OidcAccessTokenExpiresAt pgtype.Timestamptz `json:"oidc_access_token_expires_at"`
	Locale                   pgtype.Text        `json:"locale"`
	RequiresPasswordChange   bool               `json:"requires_password_change"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Email,
		arg.Roles,
		arg.RequirePasswordChange,
		arg.OidcSubjectID,
		arg.LastLogin,
		arg.UpdatedAt,
		arg.OidcAccessToken,
		arg.OidcRefreshToken,
		arg.OidcAccessTokenExpiresAt,
		arg.Locale,
		arg.RequiresPasswordChange,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Roles,
		&i.RequirePasswordChange,
		&i.OidcSubjectID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcAccessToken,
		&i.OidcRefreshToken,
		&i.OidcAccessTokenExpiresAt,
		&i.Locale,
		&i.RequiresPasswordChange,
	)
	return &i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET
    password_hash = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateUserPasswordHashParams struct {
	ID           string             `json:"id"`
	PasswordHash string             `json:"password_hash"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash, arg.UpdatedAt)
	return err
}
