// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (
    id,
    name,
    description,
    key_hash,
    key_prefix,
    user_id,
    environment_id,
    expires_at,
    last_used_at,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, name, description, key_hash, key_prefix, user_id, environment_id, expires_at, last_used_at, created_at, updated_at
`

type CreateApiKeyParams struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	KeyHash       string         `json:"key_hash"`
	KeyPrefix     string         `json:"key_prefix"`
	UserID        string         `json:"user_id"`
	EnvironmentID sql.NullString `json:"environment_id"`
	ExpiresAt     sql.NullTime   `json:"expires_at"`
	LastUsedAt    sql.NullTime   `json:"last_used_at"`
}

type CreateApiKeyRow struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	KeyHash       string         `json:"key_hash"`
	KeyPrefix     string         `json:"key_prefix"`
	UserID        string         `json:"user_id"`
	EnvironmentID sql.NullString `json:"environment_id"`
	ExpiresAt     sql.NullTime   `json:"expires_at"`
	LastUsedAt    sql.NullTime   `json:"last_used_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (*CreateApiKeyRow, error) {
	row := q.db.QueryRowContext(ctx, createApiKey,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.UserID,
		arg.EnvironmentID,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	var i CreateApiKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.UserID,
		&i.EnvironmentID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteApiKeyByID = `-- name: DeleteApiKeyByID :execrows
DELETE FROM api_keys
WHERE id = ?
`

func (q *Queries) DeleteApiKeyByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteApiKeyByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getApiKeyByID = `-- name: GetApiKeyByID :one
SELECT id, name, description, key_hash, key_prefix, user_id, environment_id, expires_at, last_used_at, created_at, updated_at
FROM api_keys
WHERE id = ?
LIMIT 1
`

type GetApiKeyByIDRow struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	KeyHash       string         `json:"key_hash"`
	KeyPrefix     string         `json:"key_prefix"`
	UserID        string         `json:"user_id"`
	EnvironmentID sql.NullString `json:"environment_id"`
	ExpiresAt     sql.NullTime   `json:"expires_at"`
	LastUsedAt    sql.NullTime   `json:"last_used_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetApiKeyByID(ctx context.Context, id string) (*GetApiKeyByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getApiKeyByID, id)
	var i GetApiKeyByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.UserID,
		&i.EnvironmentID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listApiKeys = `-- name: ListApiKeys :many
SELECT id, name, description, key_hash, key_prefix, user_id, environment_id, expires_at, last_used_at, created_at, updated_at
FROM api_keys
`

type ListApiKeysRow struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	KeyHash       string         `json:"key_hash"`
	KeyPrefix     string         `json:"key_prefix"`
	UserID        string         `json:"user_id"`
	EnvironmentID sql.NullString `json:"environment_id"`
	ExpiresAt     sql.NullTime   `json:"expires_at"`
	LastUsedAt    sql.NullTime   `json:"last_used_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListApiKeys(ctx context.Context) ([]*ListApiKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listApiKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListApiKeysRow{}
	for rows.Next() {
		var i ListApiKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.UserID,
			&i.EnvironmentID,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiKeysByPrefix = `-- name: ListApiKeysByPrefix :many
SELECT id, name, description, key_hash, key_prefix, user_id, environment_id, expires_at, last_used_at, created_at, updated_at
FROM api_keys
WHERE key_prefix = ?
`

type ListApiKeysByPrefixRow struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	KeyHash       string         `json:"key_hash"`
	KeyPrefix     string         `json:"key_prefix"`
	UserID        string         `json:"user_id"`
	EnvironmentID sql.NullString `json:"environment_id"`
	ExpiresAt     sql.NullTime   `json:"expires_at"`
	LastUsedAt    sql.NullTime   `json:"last_used_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListApiKeysByPrefix(ctx context.Context, keyPrefix string) ([]*ListApiKeysByPrefixRow, error) {
	rows, err := q.db.QueryContext(ctx, listApiKeysByPrefix, keyPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListApiKeysByPrefixRow{}
	for rows.Next() {
		var i ListApiKeysByPrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.UserID,
			&i.EnvironmentID,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchApiKeyLastUsed = `-- name: TouchApiKeyLastUsed :exec
UPDATE api_keys
SET
    last_used_at = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type TouchApiKeyLastUsedParams struct {
	LastUsedAt sql.NullTime `json:"last_used_at"`
	ID         string       `json:"id"`
}

func (q *Queries) TouchApiKeyLastUsed(ctx context.Context, arg TouchApiKeyLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, touchApiKeyLastUsed, arg.LastUsedAt, arg.ID)
	return err
}

const updateApiKey = `-- name: UpdateApiKey :exec
UPDATE api_keys
SET
    name = ?,
    description = ?,
    expires_at = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateApiKeyParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateApiKey(ctx context.Context, arg UpdateApiKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateApiKey,
		arg.Name,
		arg.Description,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
