// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apprise_settings.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const createAppriseSettings = `-- name: CreateAppriseSettings :one
INSERT INTO apprise_settings (api_url, enabled, image_update_tag, container_update_tag)
VALUES (?, ?, ?, ?)
RETURNING id, api_url, enabled, image_update_tag, container_update_tag, created_at, updated_at
`

type CreateAppriseSettingsParams struct {
	ApiUrl             string         `json:"api_url"`
	Enabled            sql.NullInt64  `json:"enabled"`
	ImageUpdateTag     sql.NullString `json:"image_update_tag"`
	ContainerUpdateTag sql.NullString `json:"container_update_tag"`
}

func (q *Queries) CreateAppriseSettings(ctx context.Context, arg CreateAppriseSettingsParams) (*AppriseSetting, error) {
	row := q.db.QueryRowContext(ctx, createAppriseSettings,
		arg.ApiUrl,
		arg.Enabled,
		arg.ImageUpdateTag,
		arg.ContainerUpdateTag,
	)
	var i AppriseSetting
	err := row.Scan(
		&i.ID,
		&i.ApiUrl,
		&i.Enabled,
		&i.ImageUpdateTag,
		&i.ContainerUpdateTag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAppriseSettings = `-- name: GetAppriseSettings :one
SELECT id, api_url, enabled, image_update_tag, container_update_tag, created_at, updated_at
FROM apprise_settings
ORDER BY id ASC
LIMIT 1
`

func (q *Queries) GetAppriseSettings(ctx context.Context) (*AppriseSetting, error) {
	row := q.db.QueryRowContext(ctx, getAppriseSettings)
	var i AppriseSetting
	err := row.Scan(
		&i.ID,
		&i.ApiUrl,
		&i.Enabled,
		&i.ImageUpdateTag,
		&i.ContainerUpdateTag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateAppriseSettings = `-- name: UpdateAppriseSettings :one
UPDATE apprise_settings
SET api_url = ?,
    enabled = ?,
    image_update_tag = ?,
    container_update_tag = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, api_url, enabled, image_update_tag, container_update_tag, created_at, updated_at
`

type UpdateAppriseSettingsParams struct {
	ApiUrl             string         `json:"api_url"`
	Enabled            sql.NullInt64  `json:"enabled"`
	ImageUpdateTag     sql.NullString `json:"image_update_tag"`
	ContainerUpdateTag sql.NullString `json:"container_update_tag"`
	ID                 int64          `json:"id"`
}

func (q *Queries) UpdateAppriseSettings(ctx context.Context, arg UpdateAppriseSettingsParams) (*AppriseSetting, error) {
	row := q.db.QueryRowContext(ctx, updateAppriseSettings,
		arg.ApiUrl,
		arg.Enabled,
		arg.ImageUpdateTag,
		arg.ContainerUpdateTag,
		arg.ID,
	)
	var i AppriseSetting
	err := row.Scan(
		&i.ID,
		&i.ApiUrl,
		&i.Enabled,
		&i.ImageUpdateTag,
		&i.ContainerUpdateTag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
