// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auto_update_records.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"

	"github.com/getarcaneapp/arcane/types/base"
)

const createAutoUpdateRecord = `-- name: CreateAutoUpdateRecord :exec
INSERT INTO auto_update_records (
    id,
    resource_id,
    resource_type,
    resource_name,
    status,
    start_time,
    end_time,
    update_available,
    update_applied,
    old_image_versions,
    new_image_versions,
    error,
    details,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type CreateAutoUpdateRecordParams struct {
	ID               string         `json:"id"`
	ResourceID       string         `json:"resource_id"`
	ResourceType     string         `json:"resource_type"`
	ResourceName     string         `json:"resource_name"`
	Status           string         `json:"status"`
	StartTime        time.Time      `json:"start_time"`
	EndTime          sql.NullTime   `json:"end_time"`
	UpdateAvailable  bool           `json:"update_available"`
	UpdateApplied    bool           `json:"update_applied"`
	OldImageVersions base.JSON      `json:"old_image_versions"`
	NewImageVersions base.JSON      `json:"new_image_versions"`
	Error            sql.NullString `json:"error"`
	Details          base.JSON      `json:"details"`
}

func (q *Queries) CreateAutoUpdateRecord(ctx context.Context, arg CreateAutoUpdateRecordParams) error {
	_, err := q.db.ExecContext(ctx, createAutoUpdateRecord,
		arg.ID,
		arg.ResourceID,
		arg.ResourceType,
		arg.ResourceName,
		arg.Status,
		arg.StartTime,
		arg.EndTime,
		arg.UpdateAvailable,
		arg.UpdateApplied,
		arg.OldImageVersions,
		arg.NewImageVersions,
		arg.Error,
		arg.Details,
	)
	return err
}

const listAutoUpdateRecords = `-- name: ListAutoUpdateRecords :many
SELECT id,
       resource_id,
       resource_type,
       resource_name,
       status,
       start_time,
       end_time,
       update_available,
       update_applied,
       old_image_versions,
       new_image_versions,
       error,
       details,
       created_at,
       updated_at
FROM auto_update_records
ORDER BY start_time DESC
`

func (q *Queries) ListAutoUpdateRecords(ctx context.Context) ([]*AutoUpdateRecord, error) {
	rows, err := q.db.QueryContext(ctx, listAutoUpdateRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AutoUpdateRecord{}
	for rows.Next() {
		var i AutoUpdateRecord
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.ResourceType,
			&i.ResourceName,
			&i.Status,
			&i.StartTime,
			&i.EndTime,
			&i.UpdateAvailable,
			&i.UpdateApplied,
			&i.OldImageVersions,
			&i.NewImageVersions,
			&i.Error,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoUpdateRecordsLimited = `-- name: ListAutoUpdateRecordsLimited :many
SELECT id,
       resource_id,
       resource_type,
       resource_name,
       status,
       start_time,
       end_time,
       update_available,
       update_applied,
       old_image_versions,
       new_image_versions,
       error,
       details,
       created_at,
       updated_at
FROM auto_update_records
ORDER BY start_time DESC
LIMIT ?
`

func (q *Queries) ListAutoUpdateRecordsLimited(ctx context.Context, limit int64) ([]*AutoUpdateRecord, error) {
	rows, err := q.db.QueryContext(ctx, listAutoUpdateRecordsLimited, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AutoUpdateRecord{}
	for rows.Next() {
		var i AutoUpdateRecord
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.ResourceType,
			&i.ResourceName,
			&i.Status,
			&i.StartTime,
			&i.EndTime,
			&i.UpdateAvailable,
			&i.UpdateApplied,
			&i.OldImageVersions,
			&i.NewImageVersions,
			&i.Error,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
