// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compose_templates.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"
)

const createComposeTemplate = `-- name: CreateComposeTemplate :one
INSERT INTO compose_templates (
    id,
    name,
    description,
    content,
    env_content,
    is_custom,
    is_remote,
    registry_id,
    meta_version,
    meta_author,
    meta_tags,
    meta_remote_url,
    meta_env_url,
    meta_documentation_url,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, content, env_content, is_custom, is_remote, registry_id, meta_version, meta_author, meta_tags, meta_remote_url, meta_env_url, meta_documentation_url, created_at, updated_at
`

type CreateComposeTemplateParams struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Description          sql.NullString `json:"description"`
	Content              sql.NullString `json:"content"`
	EnvContent           sql.NullString `json:"env_content"`
	IsCustom             bool           `json:"is_custom"`
	IsRemote             bool           `json:"is_remote"`
	RegistryID           sql.NullString `json:"registry_id"`
	MetaVersion          sql.NullString `json:"meta_version"`
	MetaAuthor           sql.NullString `json:"meta_author"`
	MetaTags             sql.NullString `json:"meta_tags"`
	MetaRemoteUrl        sql.NullString `json:"meta_remote_url"`
	MetaEnvUrl           sql.NullString `json:"meta_env_url"`
	MetaDocumentationUrl sql.NullString `json:"meta_documentation_url"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

type CreateComposeTemplateRow struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Description          sql.NullString `json:"description"`
	Content              sql.NullString `json:"content"`
	EnvContent           sql.NullString `json:"env_content"`
	IsCustom             bool           `json:"is_custom"`
	IsRemote             bool           `json:"is_remote"`
	RegistryID           sql.NullString `json:"registry_id"`
	MetaVersion          sql.NullString `json:"meta_version"`
	MetaAuthor           sql.NullString `json:"meta_author"`
	MetaTags             sql.NullString `json:"meta_tags"`
	MetaRemoteUrl        sql.NullString `json:"meta_remote_url"`
	MetaEnvUrl           sql.NullString `json:"meta_env_url"`
	MetaDocumentationUrl sql.NullString `json:"meta_documentation_url"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateComposeTemplate(ctx context.Context, arg CreateComposeTemplateParams) (*CreateComposeTemplateRow, error) {
	row := q.db.QueryRowContext(ctx, createComposeTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Content,
		arg.EnvContent,
		arg.IsCustom,
		arg.IsRemote,
		arg.RegistryID,
		arg.MetaVersion,
		arg.MetaAuthor,
		arg.MetaTags,
		arg.MetaRemoteUrl,
		arg.MetaEnvUrl,
		arg.MetaDocumentationUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateComposeTemplateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.EnvContent,
		&i.IsCustom,
		&i.IsRemote,
		&i.RegistryID,
		&i.MetaVersion,
		&i.MetaAuthor,
		&i.MetaTags,
		&i.MetaRemoteUrl,
		&i.MetaEnvUrl,
		&i.MetaDocumentationUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteComposeTemplateByID = `-- name: DeleteComposeTemplateByID :execrows
DELETE FROM compose_templates
WHERE id = ?
`

func (q *Queries) DeleteComposeTemplateByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteComposeTemplateByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findLocalComposeTemplateByDescription = `-- name: FindLocalComposeTemplateByDescription :one
SELECT id, name, description, content, env_content, is_custom, is_remote, registry_id, meta_version, meta_author, meta_tags, meta_remote_url, meta_env_url, meta_documentation_url, created_at, updated_at
FROM compose_templates
WHERE is_remote = false
  AND registry_id IS NULL
  AND description = ?
LIMIT 1
`

type FindLocalComposeTemplateByDescriptionRow struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Description          sql.NullString `json:"description"`
	Content              sql.NullString `json:"content"`
	EnvContent           sql.NullString `json:"env_content"`
	IsCustom             bool           `json:"is_custom"`
	IsRemote             bool           `json:"is_remote"`
	RegistryID           sql.NullString `json:"registry_id"`
	MetaVersion          sql.NullString `json:"meta_version"`
	MetaAuthor           sql.NullString `json:"meta_author"`
	MetaTags             sql.NullString `json:"meta_tags"`
	MetaRemoteUrl        sql.NullString `json:"meta_remote_url"`
	MetaEnvUrl           sql.NullString `json:"meta_env_url"`
	MetaDocumentationUrl sql.NullString `json:"meta_documentation_url"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

func (q *Queries) FindLocalComposeTemplateByDescription(ctx context.Context, description sql.NullString) (*FindLocalComposeTemplateByDescriptionRow, error) {
	row := q.db.QueryRowContext(ctx, findLocalComposeTemplateByDescription, description)
	var i FindLocalComposeTemplateByDescriptionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.EnvContent,
		&i.IsCustom,
		&i.IsRemote,
		&i.RegistryID,
		&i.MetaVersion,
		&i.MetaAuthor,
		&i.MetaTags,
		&i.MetaRemoteUrl,
		&i.MetaEnvUrl,
		&i.MetaDocumentationUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const findLocalComposeTemplateByDescriptionOrName = `-- name: FindLocalComposeTemplateByDescriptionOrName :one
SELECT id, name, description, content, env_content, is_custom, is_remote, registry_id, meta_version, meta_author, meta_tags, meta_remote_url, meta_env_url, meta_documentation_url, created_at, updated_at
FROM compose_templates
WHERE is_remote = false
  AND registry_id IS NULL
  AND (description = ? OR name = ?)
LIMIT 1
`

type FindLocalComposeTemplateByDescriptionOrNameParams struct {
	Description sql.NullString `json:"description"`
	Name        string         `json:"name"`
}

type FindLocalComposeTemplateByDescriptionOrNameRow struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Description          sql.NullString `json:"description"`
	Content              sql.NullString `json:"content"`
	EnvContent           sql.NullString `json:"env_content"`
	IsCustom             bool           `json:"is_custom"`
	IsRemote             bool           `json:"is_remote"`
	RegistryID           sql.NullString `json:"registry_id"`
	MetaVersion          sql.NullString `json:"meta_version"`
	MetaAuthor           sql.NullString `json:"meta_author"`
	MetaTags             sql.NullString `json:"meta_tags"`
	MetaRemoteUrl        sql.NullString `json:"meta_remote_url"`
	MetaEnvUrl           sql.NullString `json:"meta_env_url"`
	MetaDocumentationUrl sql.NullString `json:"meta_documentation_url"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

func (q *Queries) FindLocalComposeTemplateByDescriptionOrName(ctx context.Context, arg FindLocalComposeTemplateByDescriptionOrNameParams) (*FindLocalComposeTemplateByDescriptionOrNameRow, error) {
	row := q.db.QueryRowContext(ctx, findLocalComposeTemplateByDescriptionOrName, arg.Description, arg.Name)
	var i FindLocalComposeTemplateByDescriptionOrNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.EnvContent,
		&i.IsCustom,
		&i.IsRemote,
		&i.RegistryID,
		&i.MetaVersion,
		&i.MetaAuthor,
		&i.MetaTags,
		&i.MetaRemoteUrl,
		&i.MetaEnvUrl,
		&i.MetaDocumentationUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getComposeTemplateByID = `-- name: GetComposeTemplateByID :one
SELECT id, name, description, content, env_content, is_custom, is_remote, registry_id, meta_version, meta_author, meta_tags, meta_remote_url, meta_env_url, meta_documentation_url, created_at, updated_at
FROM compose_templates
WHERE id = ?
LIMIT 1
`

type GetComposeTemplateByIDRow struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Description          sql.NullString `json:"description"`
	Content              sql.NullString `json:"content"`
	EnvContent           sql.NullString `json:"env_content"`
	IsCustom             bool           `json:"is_custom"`
	IsRemote             bool           `json:"is_remote"`
	RegistryID           sql.NullString `json:"registry_id"`
	MetaVersion          sql.NullString `json:"meta_version"`
	MetaAuthor           sql.NullString `json:"meta_author"`
	MetaTags             sql.NullString `json:"meta_tags"`
	MetaRemoteUrl        sql.NullString `json:"meta_remote_url"`
	MetaEnvUrl           sql.NullString `json:"meta_env_url"`
	MetaDocumentationUrl sql.NullString `json:"meta_documentation_url"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetComposeTemplateByID(ctx context.Context, id string) (*GetComposeTemplateByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getComposeTemplateByID, id)
	var i GetComposeTemplateByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.EnvContent,
		&i.IsCustom,
		&i.IsRemote,
		&i.RegistryID,
		&i.MetaVersion,
		&i.MetaAuthor,
		&i.MetaTags,
		&i.MetaRemoteUrl,
		&i.MetaEnvUrl,
		&i.MetaDocumentationUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listComposeTemplates = `-- name: ListComposeTemplates :many
SELECT id, name, description, content, env_content, is_custom, is_remote, registry_id, meta_version, meta_author, meta_tags, meta_remote_url, meta_env_url, meta_documentation_url, created_at, updated_at
FROM compose_templates
`

type ListComposeTemplatesRow struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Description          sql.NullString `json:"description"`
	Content              sql.NullString `json:"content"`
	EnvContent           sql.NullString `json:"env_content"`
	IsCustom             bool           `json:"is_custom"`
	IsRemote             bool           `json:"is_remote"`
	RegistryID           sql.NullString `json:"registry_id"`
	MetaVersion          sql.NullString `json:"meta_version"`
	MetaAuthor           sql.NullString `json:"meta_author"`
	MetaTags             sql.NullString `json:"meta_tags"`
	MetaRemoteUrl        sql.NullString `json:"meta_remote_url"`
	MetaEnvUrl           sql.NullString `json:"meta_env_url"`
	MetaDocumentationUrl sql.NullString `json:"meta_documentation_url"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListComposeTemplates(ctx context.Context) ([]*ListComposeTemplatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listComposeTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListComposeTemplatesRow{}
	for rows.Next() {
		var i ListComposeTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Content,
			&i.EnvContent,
			&i.IsCustom,
			&i.IsRemote,
			&i.RegistryID,
			&i.MetaVersion,
			&i.MetaAuthor,
			&i.MetaTags,
			&i.MetaRemoteUrl,
			&i.MetaEnvUrl,
			&i.MetaDocumentationUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComposeTemplatesLite = `-- name: ListComposeTemplatesLite :many
SELECT id, name, description, '' AS content, NULL AS env_content, is_custom, is_remote, registry_id, meta_version, meta_author, meta_tags, meta_remote_url, meta_env_url, meta_documentation_url, created_at, updated_at
FROM compose_templates
`

type ListComposeTemplatesLiteRow struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Description          sql.NullString `json:"description"`
	Content              string         `json:"content"`
	EnvContent           interface{}    `json:"env_content"`
	IsCustom             bool           `json:"is_custom"`
	IsRemote             bool           `json:"is_remote"`
	RegistryID           sql.NullString `json:"registry_id"`
	MetaVersion          sql.NullString `json:"meta_version"`
	MetaAuthor           sql.NullString `json:"meta_author"`
	MetaTags             sql.NullString `json:"meta_tags"`
	MetaRemoteUrl        sql.NullString `json:"meta_remote_url"`
	MetaEnvUrl           sql.NullString `json:"meta_env_url"`
	MetaDocumentationUrl sql.NullString `json:"meta_documentation_url"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListComposeTemplatesLite(ctx context.Context) ([]*ListComposeTemplatesLiteRow, error) {
	rows, err := q.db.QueryContext(ctx, listComposeTemplatesLite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListComposeTemplatesLiteRow{}
	for rows.Next() {
		var i ListComposeTemplatesLiteRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Content,
			&i.EnvContent,
			&i.IsCustom,
			&i.IsRemote,
			&i.RegistryID,
			&i.MetaVersion,
			&i.MetaAuthor,
			&i.MetaTags,
			&i.MetaRemoteUrl,
			&i.MetaEnvUrl,
			&i.MetaDocumentationUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveComposeTemplate = `-- name: SaveComposeTemplate :one
UPDATE compose_templates
SET
    name = ?,
    description = ?,
    content = ?,
    env_content = ?,
    is_custom = ?,
    is_remote = ?,
    registry_id = ?,
    meta_version = ?,
    meta_author = ?,
    meta_tags = ?,
    meta_remote_url = ?,
    meta_env_url = ?,
    meta_documentation_url = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, name, description, content, env_content, is_custom, is_remote, registry_id, meta_version, meta_author, meta_tags, meta_remote_url, meta_env_url, meta_documentation_url, created_at, updated_at
`

type SaveComposeTemplateParams struct {
	Name                 string         `json:"name"`
	Description          sql.NullString `json:"description"`
	Content              sql.NullString `json:"content"`
	EnvContent           sql.NullString `json:"env_content"`
	IsCustom             bool           `json:"is_custom"`
	IsRemote             bool           `json:"is_remote"`
	RegistryID           sql.NullString `json:"registry_id"`
	MetaVersion          sql.NullString `json:"meta_version"`
	MetaAuthor           sql.NullString `json:"meta_author"`
	MetaTags             sql.NullString `json:"meta_tags"`
	MetaRemoteUrl        sql.NullString `json:"meta_remote_url"`
	MetaEnvUrl           sql.NullString `json:"meta_env_url"`
	MetaDocumentationUrl sql.NullString `json:"meta_documentation_url"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
	ID                   string         `json:"id"`
}

type SaveComposeTemplateRow struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Description          sql.NullString `json:"description"`
	Content              sql.NullString `json:"content"`
	EnvContent           sql.NullString `json:"env_content"`
	IsCustom             bool           `json:"is_custom"`
	IsRemote             bool           `json:"is_remote"`
	RegistryID           sql.NullString `json:"registry_id"`
	MetaVersion          sql.NullString `json:"meta_version"`
	MetaAuthor           sql.NullString `json:"meta_author"`
	MetaTags             sql.NullString `json:"meta_tags"`
	MetaRemoteUrl        sql.NullString `json:"meta_remote_url"`
	MetaEnvUrl           sql.NullString `json:"meta_env_url"`
	MetaDocumentationUrl sql.NullString `json:"meta_documentation_url"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

func (q *Queries) SaveComposeTemplate(ctx context.Context, arg SaveComposeTemplateParams) (*SaveComposeTemplateRow, error) {
	row := q.db.QueryRowContext(ctx, saveComposeTemplate,
		arg.Name,
		arg.Description,
		arg.Content,
		arg.EnvContent,
		arg.IsCustom,
		arg.IsRemote,
		arg.RegistryID,
		arg.MetaVersion,
		arg.MetaAuthor,
		arg.MetaTags,
		arg.MetaRemoteUrl,
		arg.MetaEnvUrl,
		arg.MetaDocumentationUrl,
		arg.UpdatedAt,
		arg.ID,
	)
	var i SaveComposeTemplateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.EnvContent,
		&i.IsCustom,
		&i.IsRemote,
		&i.RegistryID,
		&i.MetaVersion,
		&i.MetaAuthor,
		&i.MetaTags,
		&i.MetaRemoteUrl,
		&i.MetaEnvUrl,
		&i.MetaDocumentationUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
