// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"

	"github.com/getarcaneapp/arcane/types/base"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    id,
    type,
    severity,
    title,
    description,
    resource_type,
    resource_id,
    resource_name,
    user_id,
    username,
    environment_id,
    metadata,
    timestamp,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, type, severity, title, description, resource_type, resource_id, resource_name, user_id, username, environment_id, metadata, timestamp, created_at, updated_at
`

type CreateEventParams struct {
	ID            string         `json:"id"`
	Type          string         `json:"type"`
	Severity      string         `json:"severity"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	ResourceType  sql.NullString `json:"resource_type"`
	ResourceID    sql.NullString `json:"resource_id"`
	ResourceName  sql.NullString `json:"resource_name"`
	UserID        sql.NullString `json:"user_id"`
	Username      sql.NullString `json:"username"`
	EnvironmentID sql.NullString `json:"environment_id"`
	Metadata      base.JSON      `json:"metadata"`
	Timestamp     time.Time      `json:"timestamp"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (*Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.ID,
		arg.Type,
		arg.Severity,
		arg.Title,
		arg.Description,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourceName,
		arg.UserID,
		arg.Username,
		arg.EnvironmentID,
		arg.Metadata,
		arg.Timestamp,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Severity,
		&i.Title,
		&i.Description,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceName,
		&i.UserID,
		&i.Username,
		&i.EnvironmentID,
		&i.Metadata,
		&i.Timestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteEventByID = `-- name: DeleteEventByID :execrows
DELETE FROM events
WHERE id = ?
`

func (q *Queries) DeleteEventByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEventByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEventsOlderThan = `-- name: DeleteEventsOlderThan :execrows
DELETE FROM events
WHERE timestamp < ?
`

func (q *Queries) DeleteEventsOlderThan(ctx context.Context, timestamp time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEventsOlderThan, timestamp)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listEvents = `-- name: ListEvents :many
SELECT id, type, severity, title, description, resource_type, resource_id, resource_name, user_id, username, environment_id, metadata, timestamp, created_at, updated_at
FROM events
`

func (q *Queries) ListEvents(ctx context.Context) ([]*Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Severity,
			&i.Title,
			&i.Description,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceName,
			&i.UserID,
			&i.Username,
			&i.EnvironmentID,
			&i.Metadata,
			&i.Timestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
