// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: git_repositories.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"
)

const countGitOpsSyncsByRepositoryID = `-- name: CountGitOpsSyncsByRepositoryID :one
SELECT COUNT(*)
FROM gitops_syncs
WHERE repository_id = ?
`

func (q *Queries) CountGitOpsSyncsByRepositoryID(ctx context.Context, repositoryID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGitOpsSyncsByRepositoryID, repositoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGitRepository = `-- name: CreateGitRepository :one
INSERT INTO git_repositories (
    id,
    name,
    url,
    auth_type,
    username,
    token,
    ssh_key,
    description,
    enabled,
    ssh_host_key_verification,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, url, auth_type, username, token, ssh_key, description, enabled, created_at, updated_at, ssh_host_key_verification
`

type CreateGitRepositoryParams struct {
	ID                     string         `json:"id"`
	Name                   string         `json:"name"`
	Url                    string         `json:"url"`
	AuthType               string         `json:"auth_type"`
	Username               sql.NullString `json:"username"`
	Token                  sql.NullString `json:"token"`
	SshKey                 sql.NullString `json:"ssh_key"`
	Description            sql.NullString `json:"description"`
	Enabled                int64          `json:"enabled"`
	SshHostKeyVerification string         `json:"ssh_host_key_verification"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateGitRepository(ctx context.Context, arg CreateGitRepositoryParams) (*GitRepository, error) {
	row := q.db.QueryRowContext(ctx, createGitRepository,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.AuthType,
		arg.Username,
		arg.Token,
		arg.SshKey,
		arg.Description,
		arg.Enabled,
		arg.SshHostKeyVerification,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GitRepository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.AuthType,
		&i.Username,
		&i.Token,
		&i.SshKey,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SshHostKeyVerification,
	)
	return &i, err
}

const deleteGitRepositoryByID = `-- name: DeleteGitRepositoryByID :execrows
DELETE FROM git_repositories
WHERE id = ?
`

func (q *Queries) DeleteGitRepositoryByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGitRepositoryByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getGitRepositoryByID = `-- name: GetGitRepositoryByID :one
SELECT id, name, url, auth_type, username, token, ssh_key, description, enabled, created_at, updated_at, ssh_host_key_verification
FROM git_repositories
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetGitRepositoryByID(ctx context.Context, id string) (*GitRepository, error) {
	row := q.db.QueryRowContext(ctx, getGitRepositoryByID, id)
	var i GitRepository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.AuthType,
		&i.Username,
		&i.Token,
		&i.SshKey,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SshHostKeyVerification,
	)
	return &i, err
}

const getGitRepositoryByName = `-- name: GetGitRepositoryByName :one
SELECT id, name, url, auth_type, username, token, ssh_key, description, enabled, created_at, updated_at, ssh_host_key_verification
FROM git_repositories
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetGitRepositoryByName(ctx context.Context, name string) (*GitRepository, error) {
	row := q.db.QueryRowContext(ctx, getGitRepositoryByName, name)
	var i GitRepository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.AuthType,
		&i.Username,
		&i.Token,
		&i.SshKey,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SshHostKeyVerification,
	)
	return &i, err
}

const listGitRepositories = `-- name: ListGitRepositories :many
SELECT id, name, url, auth_type, username, token, ssh_key, description, enabled, created_at, updated_at, ssh_host_key_verification
FROM git_repositories
`

func (q *Queries) ListGitRepositories(ctx context.Context) ([]*GitRepository, error) {
	rows, err := q.db.QueryContext(ctx, listGitRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GitRepository{}
	for rows.Next() {
		var i GitRepository
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.AuthType,
			&i.Username,
			&i.Token,
			&i.SshKey,
			&i.Description,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SshHostKeyVerification,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveGitRepository = `-- name: SaveGitRepository :one
UPDATE git_repositories
SET
    name = ?,
    url = ?,
    auth_type = ?,
    username = ?,
    token = ?,
    ssh_key = ?,
    description = ?,
    enabled = ?,
    ssh_host_key_verification = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, name, url, auth_type, username, token, ssh_key, description, enabled, created_at, updated_at, ssh_host_key_verification
`

type SaveGitRepositoryParams struct {
	Name                   string         `json:"name"`
	Url                    string         `json:"url"`
	AuthType               string         `json:"auth_type"`
	Username               sql.NullString `json:"username"`
	Token                  sql.NullString `json:"token"`
	SshKey                 sql.NullString `json:"ssh_key"`
	Description            sql.NullString `json:"description"`
	Enabled                int64          `json:"enabled"`
	SshHostKeyVerification string         `json:"ssh_host_key_verification"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
	ID                     string         `json:"id"`
}

func (q *Queries) SaveGitRepository(ctx context.Context, arg SaveGitRepositoryParams) (*GitRepository, error) {
	row := q.db.QueryRowContext(ctx, saveGitRepository,
		arg.Name,
		arg.Url,
		arg.AuthType,
		arg.Username,
		arg.Token,
		arg.SshKey,
		arg.Description,
		arg.Enabled,
		arg.SshHostKeyVerification,
		arg.UpdatedAt,
		arg.ID,
	)
	var i GitRepository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.AuthType,
		&i.Username,
		&i.Token,
		&i.SshKey,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SshHostKeyVerification,
	)
	return &i, err
}
