// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gitops_syncs.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"
)

const clearProjectGitOpsManagedByIfMatches = `-- name: ClearProjectGitOpsManagedByIfMatches :exec
UPDATE projects
SET gitops_managed_by = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
  AND gitops_managed_by = ?
`

type ClearProjectGitOpsManagedByIfMatchesParams struct {
	ID              string         `json:"id"`
	GitopsManagedBy sql.NullString `json:"gitops_managed_by"`
}

func (q *Queries) ClearProjectGitOpsManagedByIfMatches(ctx context.Context, arg ClearProjectGitOpsManagedByIfMatchesParams) error {
	_, err := q.db.ExecContext(ctx, clearProjectGitOpsManagedByIfMatches, arg.ID, arg.GitopsManagedBy)
	return err
}

const createGitOpsSync = `-- name: CreateGitOpsSync :one
INSERT INTO gitops_syncs (
    id,
    name,
    environment_id,
    repository_id,
    branch,
    compose_path,
    project_name,
    project_id,
    auto_sync,
    sync_interval,
    last_sync_at,
    last_sync_status,
    last_sync_error,
    last_sync_commit,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, environment_id, repository_id, branch, compose_path, project_name, project_id, auto_sync, sync_interval, last_sync_at, last_sync_status, last_sync_error, last_sync_commit, created_at, updated_at
`

type CreateGitOpsSyncParams struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	EnvironmentID  string         `json:"environment_id"`
	RepositoryID   string         `json:"repository_id"`
	Branch         string         `json:"branch"`
	ComposePath    string         `json:"compose_path"`
	ProjectName    string         `json:"project_name"`
	ProjectID      sql.NullString `json:"project_id"`
	AutoSync       bool           `json:"auto_sync"`
	SyncInterval   int64          `json:"sync_interval"`
	LastSyncAt     sql.NullTime   `json:"last_sync_at"`
	LastSyncStatus sql.NullString `json:"last_sync_status"`
	LastSyncError  sql.NullString `json:"last_sync_error"`
	LastSyncCommit sql.NullString `json:"last_sync_commit"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) CreateGitOpsSync(ctx context.Context, arg CreateGitOpsSyncParams) (*GitopsSync, error) {
	row := q.db.QueryRowContext(ctx, createGitOpsSync,
		arg.ID,
		arg.Name,
		arg.EnvironmentID,
		arg.RepositoryID,
		arg.Branch,
		arg.ComposePath,
		arg.ProjectName,
		arg.ProjectID,
		arg.AutoSync,
		arg.SyncInterval,
		arg.LastSyncAt,
		arg.LastSyncStatus,
		arg.LastSyncError,
		arg.LastSyncCommit,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GitopsSync
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EnvironmentID,
		&i.RepositoryID,
		&i.Branch,
		&i.ComposePath,
		&i.ProjectName,
		&i.ProjectID,
		&i.AutoSync,
		&i.SyncInterval,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.LastSyncError,
		&i.LastSyncCommit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteGitOpsSyncByID = `-- name: DeleteGitOpsSyncByID :execrows
DELETE FROM gitops_syncs
WHERE id = ?
`

func (q *Queries) DeleteGitOpsSyncByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGitOpsSyncByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getGitOpsSyncByID = `-- name: GetGitOpsSyncByID :one
SELECT id, name, environment_id, repository_id, branch, compose_path, project_name, project_id, auto_sync, sync_interval, last_sync_at, last_sync_status, last_sync_error, last_sync_commit, created_at, updated_at
FROM gitops_syncs
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetGitOpsSyncByID(ctx context.Context, id string) (*GitopsSync, error) {
	row := q.db.QueryRowContext(ctx, getGitOpsSyncByID, id)
	var i GitopsSync
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EnvironmentID,
		&i.RepositoryID,
		&i.Branch,
		&i.ComposePath,
		&i.ProjectName,
		&i.ProjectID,
		&i.AutoSync,
		&i.SyncInterval,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.LastSyncError,
		&i.LastSyncCommit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAutoSyncGitOpsSyncs = `-- name: ListAutoSyncGitOpsSyncs :many
SELECT id, name, environment_id, repository_id, branch, compose_path, project_name, project_id, auto_sync, sync_interval, last_sync_at, last_sync_status, last_sync_error, last_sync_commit, created_at, updated_at
FROM gitops_syncs
WHERE auto_sync = true
`

func (q *Queries) ListAutoSyncGitOpsSyncs(ctx context.Context) ([]*GitopsSync, error) {
	rows, err := q.db.QueryContext(ctx, listAutoSyncGitOpsSyncs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GitopsSync{}
	for rows.Next() {
		var i GitopsSync
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EnvironmentID,
			&i.RepositoryID,
			&i.Branch,
			&i.ComposePath,
			&i.ProjectName,
			&i.ProjectID,
			&i.AutoSync,
			&i.SyncInterval,
			&i.LastSyncAt,
			&i.LastSyncStatus,
			&i.LastSyncError,
			&i.LastSyncCommit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitOpsSyncs = `-- name: ListGitOpsSyncs :many
SELECT id, name, environment_id, repository_id, branch, compose_path, project_name, project_id, auto_sync, sync_interval, last_sync_at, last_sync_status, last_sync_error, last_sync_commit, created_at, updated_at
FROM gitops_syncs
`

func (q *Queries) ListGitOpsSyncs(ctx context.Context) ([]*GitopsSync, error) {
	rows, err := q.db.QueryContext(ctx, listGitOpsSyncs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GitopsSync{}
	for rows.Next() {
		var i GitopsSync
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EnvironmentID,
			&i.RepositoryID,
			&i.Branch,
			&i.ComposePath,
			&i.ProjectName,
			&i.ProjectID,
			&i.AutoSync,
			&i.SyncInterval,
			&i.LastSyncAt,
			&i.LastSyncStatus,
			&i.LastSyncError,
			&i.LastSyncCommit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitOpsSyncsByEnvironment = `-- name: ListGitOpsSyncsByEnvironment :many
SELECT id, name, environment_id, repository_id, branch, compose_path, project_name, project_id, auto_sync, sync_interval, last_sync_at, last_sync_status, last_sync_error, last_sync_commit, created_at, updated_at
FROM gitops_syncs
WHERE environment_id = ?
`

func (q *Queries) ListGitOpsSyncsByEnvironment(ctx context.Context, environmentID string) ([]*GitopsSync, error) {
	rows, err := q.db.QueryContext(ctx, listGitOpsSyncsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GitopsSync{}
	for rows.Next() {
		var i GitopsSync
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EnvironmentID,
			&i.RepositoryID,
			&i.Branch,
			&i.ComposePath,
			&i.ProjectName,
			&i.ProjectID,
			&i.AutoSync,
			&i.SyncInterval,
			&i.LastSyncAt,
			&i.LastSyncStatus,
			&i.LastSyncError,
			&i.LastSyncCommit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveGitOpsSync = `-- name: SaveGitOpsSync :one
UPDATE gitops_syncs
SET
    name = ?,
    environment_id = ?,
    repository_id = ?,
    branch = ?,
    compose_path = ?,
    project_name = ?,
    project_id = ?,
    auto_sync = ?,
    sync_interval = ?,
    last_sync_at = ?,
    last_sync_status = ?,
    last_sync_error = ?,
    last_sync_commit = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, name, environment_id, repository_id, branch, compose_path, project_name, project_id, auto_sync, sync_interval, last_sync_at, last_sync_status, last_sync_error, last_sync_commit, created_at, updated_at
`

type SaveGitOpsSyncParams struct {
	Name           string         `json:"name"`
	EnvironmentID  string         `json:"environment_id"`
	RepositoryID   string         `json:"repository_id"`
	Branch         string         `json:"branch"`
	ComposePath    string         `json:"compose_path"`
	ProjectName    string         `json:"project_name"`
	ProjectID      sql.NullString `json:"project_id"`
	AutoSync       bool           `json:"auto_sync"`
	SyncInterval   int64          `json:"sync_interval"`
	LastSyncAt     sql.NullTime   `json:"last_sync_at"`
	LastSyncStatus sql.NullString `json:"last_sync_status"`
	LastSyncError  sql.NullString `json:"last_sync_error"`
	LastSyncCommit sql.NullString `json:"last_sync_commit"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) SaveGitOpsSync(ctx context.Context, arg SaveGitOpsSyncParams) (*GitopsSync, error) {
	row := q.db.QueryRowContext(ctx, saveGitOpsSync,
		arg.Name,
		arg.EnvironmentID,
		arg.RepositoryID,
		arg.Branch,
		arg.ComposePath,
		arg.ProjectName,
		arg.ProjectID,
		arg.AutoSync,
		arg.SyncInterval,
		arg.LastSyncAt,
		arg.LastSyncStatus,
		arg.LastSyncError,
		arg.LastSyncCommit,
		arg.UpdatedAt,
		arg.ID,
	)
	var i GitopsSync
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EnvironmentID,
		&i.RepositoryID,
		&i.Branch,
		&i.ComposePath,
		&i.ProjectName,
		&i.ProjectID,
		&i.AutoSync,
		&i.SyncInterval,
		&i.LastSyncAt,
		&i.LastSyncStatus,
		&i.LastSyncError,
		&i.LastSyncCommit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const setProjectGitOpsManagedBy = `-- name: SetProjectGitOpsManagedBy :exec
UPDATE projects
SET gitops_managed_by = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetProjectGitOpsManagedByParams struct {
	GitopsManagedBy sql.NullString `json:"gitops_managed_by"`
	ID              string         `json:"id"`
}

func (q *Queries) SetProjectGitOpsManagedBy(ctx context.Context, arg SetProjectGitOpsManagedByParams) error {
	_, err := q.db.ExecContext(ctx, setProjectGitOpsManagedBy, arg.GitopsManagedBy, arg.ID)
	return err
}

const updateGitOpsSyncInterval = `-- name: UpdateGitOpsSyncInterval :exec
UPDATE gitops_syncs
SET sync_interval = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateGitOpsSyncIntervalParams struct {
	SyncInterval int64  `json:"sync_interval"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateGitOpsSyncInterval(ctx context.Context, arg UpdateGitOpsSyncIntervalParams) error {
	_, err := q.db.ExecContext(ctx, updateGitOpsSyncInterval, arg.SyncInterval, arg.ID)
	return err
}

const updateGitOpsSyncProjectID = `-- name: UpdateGitOpsSyncProjectID :exec
UPDATE gitops_syncs
SET project_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateGitOpsSyncProjectIDParams struct {
	ProjectID sql.NullString `json:"project_id"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateGitOpsSyncProjectID(ctx context.Context, arg UpdateGitOpsSyncProjectIDParams) error {
	_, err := q.db.ExecContext(ctx, updateGitOpsSyncProjectID, arg.ProjectID, arg.ID)
	return err
}

const updateGitOpsSyncStatus = `-- name: UpdateGitOpsSyncStatus :exec
UPDATE gitops_syncs
SET
    last_sync_at = ?,
    last_sync_status = ?,
    last_sync_error = ?,
    last_sync_commit = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateGitOpsSyncStatusParams struct {
	LastSyncAt     sql.NullTime   `json:"last_sync_at"`
	LastSyncStatus sql.NullString `json:"last_sync_status"`
	LastSyncError  sql.NullString `json:"last_sync_error"`
	LastSyncCommit sql.NullString `json:"last_sync_commit"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateGitOpsSyncStatus(ctx context.Context, arg UpdateGitOpsSyncStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateGitOpsSyncStatus,
		arg.LastSyncAt,
		arg.LastSyncStatus,
		arg.LastSyncError,
		arg.LastSyncCommit,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
