// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"database/sql"
	"time"

	"github.com/getarcaneapp/arcane/types/base"
)

type ApiKey struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	KeyHash       string         `json:"key_hash"`
	KeyPrefix     string         `json:"key_prefix"`
	UserID        string         `json:"user_id"`
	ExpiresAt     sql.NullTime   `json:"expires_at"`
	LastUsedAt    sql.NullTime   `json:"last_used_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	EnvironmentID sql.NullString `json:"environment_id"`
}

type AppriseSetting struct {
	ID                 int64          `json:"id"`
	ApiUrl             string         `json:"api_url"`
	Enabled            sql.NullInt64  `json:"enabled"`
	ImageUpdateTag     sql.NullString `json:"image_update_tag"`
	ContainerUpdateTag sql.NullString `json:"container_update_tag"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type AutoUpdateRecord struct {
	ID               string         `json:"id"`
	ResourceID       string         `json:"resource_id"`
	ResourceType     string         `json:"resource_type"`
	ResourceName     string         `json:"resource_name"`
	Status           string         `json:"status"`
	StartTime        time.Time      `json:"start_time"`
	EndTime          sql.NullTime   `json:"end_time"`
	UpdateAvailable  bool           `json:"update_available"`
	UpdateApplied    bool           `json:"update_applied"`
	OldImageVersions base.JSON      `json:"old_image_versions"`
	NewImageVersions base.JSON      `json:"new_image_versions"`
	Error            sql.NullString `json:"error"`
	Details          base.JSON      `json:"details"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type ComposeTemplate struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Description          sql.NullString `json:"description"`
	Content              sql.NullString `json:"content"`
	EnvContent           sql.NullString `json:"env_content"`
	IsCustom             bool           `json:"is_custom"`
	IsRemote             bool           `json:"is_remote"`
	RegistryID           sql.NullString `json:"registry_id"`
	MetaVersion          sql.NullString `json:"meta_version"`
	MetaAuthor           sql.NullString `json:"meta_author"`
	MetaTags             sql.NullString `json:"meta_tags"`
	MetaRemoteUrl        sql.NullString `json:"meta_remote_url"`
	MetaEnvUrl           sql.NullString `json:"meta_env_url"`
	MetaDocumentationUrl sql.NullString `json:"meta_documentation_url"`
	MetaIconUrl          sql.NullString `json:"meta_icon_url"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

type ContainerRegistry struct {
	ID          string         `json:"id"`
	Url         string         `json:"url"`
	Username    string         `json:"username"`
	Token       string         `json:"token"`
	Description sql.NullString `json:"description"`
	Insecure    bool           `json:"insecure"`
	Enabled     bool           `json:"enabled"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Environment struct {
	ID          string         `json:"id"`
	ApiUrl      string         `json:"api_url"`
	Status      string         `json:"status"`
	Enabled     bool           `json:"enabled"`
	LastSeen    sql.NullTime   `json:"last_seen"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	AccessToken sql.NullString `json:"access_token"`
	Name        sql.NullString `json:"name"`
	ApiKeyID    sql.NullString `json:"api_key_id"`
	IsEdge      int64          `json:"is_edge"`
}

type Event struct {
	ID            string         `json:"id"`
	Type          string         `json:"type"`
	Severity      string         `json:"severity"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	ResourceType  sql.NullString `json:"resource_type"`
	ResourceID    sql.NullString `json:"resource_id"`
	ResourceName  sql.NullString `json:"resource_name"`
	UserID        sql.NullString `json:"user_id"`
	Username      sql.NullString `json:"username"`
	EnvironmentID sql.NullString `json:"environment_id"`
	Metadata      base.JSON      `json:"metadata"`
	Timestamp     time.Time      `json:"timestamp"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type GitRepository struct {
	ID                     string         `json:"id"`
	Name                   string         `json:"name"`
	Url                    string         `json:"url"`
	AuthType               string         `json:"auth_type"`
	Username               sql.NullString `json:"username"`
	Token                  sql.NullString `json:"token"`
	SshKey                 sql.NullString `json:"ssh_key"`
	Description            sql.NullString `json:"description"`
	Enabled                int64          `json:"enabled"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
	SshHostKeyVerification string         `json:"ssh_host_key_verification"`
}

type GitopsSync struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	EnvironmentID  string         `json:"environment_id"`
	RepositoryID   string         `json:"repository_id"`
	Branch         string         `json:"branch"`
	ComposePath    string         `json:"compose_path"`
	ProjectName    string         `json:"project_name"`
	ProjectID      sql.NullString `json:"project_id"`
	AutoSync       bool           `json:"auto_sync"`
	SyncInterval   int64          `json:"sync_interval"`
	LastSyncAt     sql.NullTime   `json:"last_sync_at"`
	LastSyncStatus sql.NullString `json:"last_sync_status"`
	LastSyncError  sql.NullString `json:"last_sync_error"`
	LastSyncCommit sql.NullString `json:"last_sync_commit"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type Image struct {
	ID          string         `json:"id"`
	RepoTags    base.JSON      `json:"repo_tags"`
	RepoDigests base.JSON      `json:"repo_digests"`
	Size        int64          `json:"size"`
	VirtualSize int64          `json:"virtual_size"`
	Labels      base.JSON      `json:"labels"`
	Created     time.Time      `json:"created"`
	Repo        sql.NullString `json:"repo"`
	Tag         sql.NullString `json:"tag"`
	InUse       bool           `json:"in_use"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ImageUpdate struct {
	ID               string         `json:"id"`
	Repository       string         `json:"repository"`
	Tag              string         `json:"tag"`
	HasUpdate        bool           `json:"has_update"`
	UpdateType       sql.NullString `json:"update_type"`
	CurrentVersion   string         `json:"current_version"`
	LatestVersion    sql.NullString `json:"latest_version"`
	CurrentDigest    sql.NullString `json:"current_digest"`
	LatestDigest     sql.NullString `json:"latest_digest"`
	CheckTime        time.Time      `json:"check_time"`
	ResponseTimeMs   int64          `json:"response_time_ms"`
	LastError        sql.NullString `json:"last_error"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	AuthMethod       sql.NullString `json:"auth_method"`
	AuthUsername     sql.NullString `json:"auth_username"`
	AuthRegistry     sql.NullString `json:"auth_registry"`
	UsedCredential   sql.NullInt64  `json:"used_credential"`
	NotificationSent sql.NullInt64  `json:"notification_sent"`
}

type NotificationLog struct {
	ID        int64          `json:"id"`
	Provider  string         `json:"provider"`
	ImageRef  string         `json:"image_ref"`
	Status    string         `json:"status"`
	Error     sql.NullString `json:"error"`
	Metadata  base.JSON      `json:"metadata"`
	SentAt    time.Time      `json:"sent_at"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type NotificationSetting struct {
	ID        int64        `json:"id"`
	Provider  string       `json:"provider"`
	Enabled   sql.NullBool `json:"enabled"`
	Config    base.JSON    `json:"config"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Project struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	DirName         sql.NullString `json:"dir_name"`
	Path            string         `json:"path"`
	Status          string         `json:"status"`
	ServiceCount    int64          `json:"service_count"`
	RunningCount    int64          `json:"running_count"`
	AutoUpdate      bool           `json:"auto_update"`
	IsExternal      bool           `json:"is_external"`
	IsLegacy        bool           `json:"is_legacy"`
	IsRemote        bool           `json:"is_remote"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	StatusReason    sql.NullString `json:"status_reason"`
	GitopsManagedBy sql.NullString `json:"gitops_managed_by"`
}

type Setting struct {
	Key        string       `json:"key"`
	Value      string       `json:"value"`
	Type       string       `json:"type"`
	Ispublic   bool         `json:"ispublic"`
	Isinternal bool         `json:"isinternal"`
	Createdat  time.Time    `json:"createdat"`
	Updatedat  sql.NullTime `json:"updatedat"`
}

type TemplateRegistry struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Url         string         `json:"url"`
	Enabled     bool           `json:"enabled"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID                       string           `json:"id"`
	Username                 string           `json:"username"`
	PasswordHash             string           `json:"password_hash"`
	DisplayName              sql.NullString   `json:"display_name"`
	Email                    sql.NullString   `json:"email"`
	Roles                    base.StringSlice `json:"roles"`
	RequirePasswordChange    bool             `json:"require_password_change"`
	OidcSubjectID            sql.NullString   `json:"oidc_subject_id"`
	LastLogin                sql.NullTime     `json:"last_login"`
	CreatedAt                time.Time        `json:"created_at"`
	UpdatedAt                sql.NullTime     `json:"updated_at"`
	OidcAccessToken          sql.NullString   `json:"oidc_access_token"`
	OidcRefreshToken         sql.NullString   `json:"oidc_refresh_token"`
	OidcAccessTokenExpiresAt sql.NullTime     `json:"oidc_access_token_expires_at"`
	Locale                   sql.NullString   `json:"locale"`
	RequiresPasswordChange   bool             `json:"requires_password_change"`
}

type VolumeBackup struct {
	ID         string       `json:"id"`
	VolumeName string       `json:"volume_name"`
	Size       int64        `json:"size"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}
