// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_logs.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"

	"github.com/getarcaneapp/arcane/types/base"
)

const createNotificationLog = `-- name: CreateNotificationLog :exec
INSERT INTO notification_logs (provider, image_ref, status, error, metadata, sent_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateNotificationLogParams struct {
	Provider string         `json:"provider"`
	ImageRef string         `json:"image_ref"`
	Status   string         `json:"status"`
	Error    sql.NullString `json:"error"`
	Metadata base.JSON      `json:"metadata"`
	SentAt   time.Time      `json:"sent_at"`
}

func (q *Queries) CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) error {
	_, err := q.db.ExecContext(ctx, createNotificationLog,
		arg.Provider,
		arg.ImageRef,
		arg.Status,
		arg.Error,
		arg.Metadata,
		arg.SentAt,
	)
	return err
}
