// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlitedb

import (
	"context"
	"strings"
)

const deleteSetting = `-- name: DeleteSetting :execrows
DELETE FROM settings
WHERE key = ?
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSetting, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSettingsNotIn = `-- name: DeleteSettingsNotIn :execrows
DELETE FROM settings
WHERE key NOT IN (/*SLICE:keys*/?)
`

func (q *Queries) DeleteSettingsNotIn(ctx context.Context, keys []string) (int64, error) {
	query := deleteSettingsNotIn
	var queryParams []interface{}
	if len(keys) > 0 {
		for _, v := range keys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:keys*/?", strings.Repeat(",?", len(keys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:keys*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSetting = `-- name: GetSetting :one
SELECT key, value
FROM settings
WHERE key = ?
LIMIT 1
`

type GetSettingRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetSetting(ctx context.Context, key string) (*GetSettingRow, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i GetSettingRow
	err := row.Scan(&i.Key, &i.Value)
	return &i, err
}

const insertSettingIfNotExists = `-- name: InsertSettingIfNotExists :exec
INSERT INTO settings (key, value)
VALUES (?, ?)
ON CONFLICT (key) DO NOTHING
`

type InsertSettingIfNotExistsParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) InsertSettingIfNotExists(ctx context.Context, arg InsertSettingIfNotExistsParams) error {
	_, err := q.db.ExecContext(ctx, insertSettingIfNotExists, arg.Key, arg.Value)
	return err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value
FROM settings
`

type ListSettingsRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) ListSettings(ctx context.Context) ([]*ListSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListSettingsRow{}
	for rows.Next() {
		var i ListSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettingKey = `-- name: UpdateSettingKey :exec
UPDATE settings
SET key = ?
WHERE key = ?
`

type UpdateSettingKeyParams struct {
	Key   string `json:"key"`
	Key_2 string `json:"key_2"`
}

func (q *Queries) UpdateSettingKey(ctx context.Context, arg UpdateSettingKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateSettingKey, arg.Key, arg.Key_2)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value)
VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
