// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"

	"github.com/getarcaneapp/arcane/types/base"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    username,
    password_hash,
    display_name,
    email,
    roles,
    require_password_change,
    oidc_subject_id,
    last_login,
    created_at,
    updated_at,
    oidc_access_token,
    oidc_refresh_token,
    oidc_access_token_expires_at,
    locale,
    requires_password_change
)
VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
`

type CreateUserParams struct {
	ID                       string           `json:"id"`
	Username                 string           `json:"username"`
	PasswordHash             string           `json:"password_hash"`
	DisplayName              sql.NullString   `json:"display_name"`
	Email                    sql.NullString   `json:"email"`
	Roles                    base.StringSlice `json:"roles"`
	RequirePasswordChange    bool             `json:"require_password_change"`
	OidcSubjectID            sql.NullString   `json:"oidc_subject_id"`
	LastLogin                sql.NullTime     `json:"last_login"`
	CreatedAt                time.Time        `json:"created_at"`
	UpdatedAt                sql.NullTime     `json:"updated_at"`
	OidcAccessToken          sql.NullString   `json:"oidc_access_token"`
	OidcRefreshToken         sql.NullString   `json:"oidc_refresh_token"`
	OidcAccessTokenExpiresAt sql.NullTime     `json:"oidc_access_token_expires_at"`
	Locale                   sql.NullString   `json:"locale"`
	RequiresPasswordChange   bool             `json:"requires_password_change"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Email,
		arg.Roles,
		arg.RequirePasswordChange,
		arg.OidcSubjectID,
		arg.LastLogin,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.OidcAccessToken,
		arg.OidcRefreshToken,
		arg.OidcAccessTokenExpiresAt,
		arg.Locale,
		arg.RequiresPasswordChange,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Roles,
		&i.RequirePasswordChange,
		&i.OidcSubjectID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcAccessToken,
		&i.OidcRefreshToken,
		&i.OidcAccessTokenExpiresAt,
		&i.Locale,
		&i.RequiresPasswordChange,
	)
	return &i, err
}

const deleteUserByID = `-- name: DeleteUserByID :execrows
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUserByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
FROM users
WHERE email = ?
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Roles,
		&i.RequirePasswordChange,
		&i.OidcSubjectID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcAccessToken,
		&i.OidcRefreshToken,
		&i.OidcAccessTokenExpiresAt,
		&i.Locale,
		&i.RequiresPasswordChange,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Roles,
		&i.RequirePasswordChange,
		&i.OidcSubjectID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcAccessToken,
		&i.OidcRefreshToken,
		&i.OidcAccessTokenExpiresAt,
		&i.Locale,
		&i.RequiresPasswordChange,
	)
	return &i, err
}

const getUserByIDForUpdate = `-- name: GetUserByIDForUpdate :one
SELECT id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserByIDForUpdate(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByIDForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Roles,
		&i.RequirePasswordChange,
		&i.OidcSubjectID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcAccessToken,
		&i.OidcRefreshToken,
		&i.OidcAccessTokenExpiresAt,
		&i.Locale,
		&i.RequiresPasswordChange,
	)
	return &i, err
}

const getUserByOidcSubjectID = `-- name: GetUserByOidcSubjectID :one
SELECT id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
FROM users
WHERE oidc_subject_id = ?
LIMIT 1
`

func (q *Queries) GetUserByOidcSubjectID(ctx context.Context, oidcSubjectID sql.NullString) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByOidcSubjectID, oidcSubjectID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Roles,
		&i.RequirePasswordChange,
		&i.OidcSubjectID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcAccessToken,
		&i.OidcRefreshToken,
		&i.OidcAccessTokenExpiresAt,
		&i.Locale,
		&i.RequiresPasswordChange,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
FROM users
WHERE username = ?
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Roles,
		&i.RequirePasswordChange,
		&i.OidcSubjectID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcAccessToken,
		&i.OidcRefreshToken,
		&i.OidcAccessTokenExpiresAt,
		&i.Locale,
		&i.RequiresPasswordChange,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.DisplayName,
			&i.Email,
			&i.Roles,
			&i.RequirePasswordChange,
			&i.OidcSubjectID,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OidcAccessToken,
			&i.OidcRefreshToken,
			&i.OidcAccessTokenExpiresAt,
			&i.Locale,
			&i.RequiresPasswordChange,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username = ?,
    password_hash = ?,
    display_name = ?,
    email = ?,
    roles = ?,
    require_password_change = ?,
    oidc_subject_id = ?,
    last_login = ?,
    updated_at = ?,
    oidc_access_token = ?,
    oidc_refresh_token = ?,
    oidc_access_token_expires_at = ?,
    locale = ?,
    requires_password_change = ?
WHERE id = ?
RETURNING id, username, password_hash, display_name, email, roles, require_password_change, oidc_subject_id, last_login, created_at, updated_at, oidc_access_token, oidc_refresh_token, oidc_access_token_expires_at, locale, requires_password_change
`

type UpdateUserParams struct {
	Username                 string           `json:"username"`
	PasswordHash             string           `json:"password_hash"`
	DisplayName              sql.NullString   `json:"display_name"`
	Email                    sql.NullString   `json:"email"`
	Roles                    base.StringSlice `json:"roles"`
	RequirePasswordChange    bool             `json:"require_password_change"`
	OidcSubjectID            sql.NullString   `json:"oidc_subject_id"`
	LastLogin                sql.NullTime     `json:"last_login"`
	UpdatedAt                sql.NullTime     `json:"updated_at"`
	OidcAccessToken          sql.NullString   `json:"oidc_access_token"`
	OidcRefreshToken         sql.NullString   `json:"oidc_refresh_token"`
	OidcAccessTokenExpiresAt sql.NullTime     `json:"oidc_access_token_expires_at"`
	Locale                   sql.NullString   `json:"locale"`
	RequiresPasswordChange   bool             `json:"requires_password_change"`
	ID                       string           `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Email,
		arg.Roles,
		arg.RequirePasswordChange,
		arg.OidcSubjectID,
		arg.LastLogin,
		arg.UpdatedAt,
		arg.OidcAccessToken,
		arg.OidcRefreshToken,
		arg.OidcAccessTokenExpiresAt,
		arg.Locale,
		arg.RequiresPasswordChange,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Roles,
		&i.RequirePasswordChange,
		&i.OidcSubjectID,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcAccessToken,
		&i.OidcRefreshToken,
		&i.OidcAccessTokenExpiresAt,
		&i.Locale,
		&i.RequiresPasswordChange,
	)
	return &i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET
    password_hash = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateUserPasswordHashParams struct {
	PasswordHash string       `json:"password_hash"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	ID           string       `json:"id"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasswordHash, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}
