// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: volumes.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"
)

const createVolumeBackup = `-- name: CreateVolumeBackup :one
INSERT INTO volume_backups (
    id,
    volume_name,
    size,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?)
RETURNING id, volume_name, size, created_at, updated_at
`

type CreateVolumeBackupParams struct {
	ID         string       `json:"id"`
	VolumeName string       `json:"volume_name"`
	Size       int64        `json:"size"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

func (q *Queries) CreateVolumeBackup(ctx context.Context, arg CreateVolumeBackupParams) (*VolumeBackup, error) {
	row := q.db.QueryRowContext(ctx, createVolumeBackup,
		arg.ID,
		arg.VolumeName,
		arg.Size,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i VolumeBackup
	err := row.Scan(
		&i.ID,
		&i.VolumeName,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteVolumeBackupByID = `-- name: DeleteVolumeBackupByID :execrows
DELETE FROM volume_backups
WHERE id = ?
`

func (q *Queries) DeleteVolumeBackupByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVolumeBackupByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getVolumeBackupByID = `-- name: GetVolumeBackupByID :one
SELECT id, volume_name, size, created_at, updated_at
FROM volume_backups
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetVolumeBackupByID(ctx context.Context, id string) (*VolumeBackup, error) {
	row := q.db.QueryRowContext(ctx, getVolumeBackupByID, id)
	var i VolumeBackup
	err := row.Scan(
		&i.ID,
		&i.VolumeName,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listVolumeBackupsByVolumeName = `-- name: ListVolumeBackupsByVolumeName :many
SELECT id, volume_name, size, created_at, updated_at
FROM volume_backups
WHERE volume_name = ?
`

func (q *Queries) ListVolumeBackupsByVolumeName(ctx context.Context, volumeName string) ([]*VolumeBackup, error) {
	rows, err := q.db.QueryContext(ctx, listVolumeBackupsByVolumeName, volumeName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*VolumeBackup{}
	for rows.Next() {
		var i VolumeBackup
		if err := rows.Scan(
			&i.ID,
			&i.VolumeName,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
